=head1 IupClassMatch (since 3.4)

Checks if the give class name matches the class name of the given
interface element.

=head2 Parameters/Return

 int IupClassMatch(Ihandle* ih, const char* classname); [in C]
 iup.ClassMatch(ih: ihandle, classname: string) -> (ret: boolean) [in Lua]

B<ih>: Identifier of the interface element.

B<classname>: name of the class to match.

Returns: true (1) if the given name matches the class name or one of
its parent class names, false (0) or else.

=head2 See Also

L<IupGetClassName|iupgetclassname.html>

=cut