=head1 IupConvertXYToPos (since 3.0)

Converts a (x,y) coordinate in an item position.

=head2 Parameters/Return

 int IupConvertXYToPos(Ihandle *ih, int x, int y); [in C]
 iup.ConvertXYToPos(ih: ihandle, x, y: number) -> (ret: number) [in Lua]

B<ih>: Identifier of the element.

B<x>: X coordinate relative to the left corner of the element.

B<y>: Y coordinate relative to the top corner of the element.

Returns: the position starting at 0 (except for B<IupList> that starts
at 1). If fails returns -1.

=head2 Notes

It can be used for B<IupText> and B<IupScintilla> (returns a position
in the string), B<IupList> (returns an item), B<IupTree> (returns a
node identifier) or B<IupMatrix> (returns a cell position, where
pos=lin*numcol + col).

=head2 See Also

L<IupText|../elem/iuptext.html>, L<IupList|../elem/iuplist.html>,
L<IupTree|../elem/iuptree.html>, L< IupMatrix|../ctrl/iupmatrix.html>,
L<IupScintilla|../ctrl/iup_scintilla.html>

=cut