=head1 IupConvertXYToPos (since 3.0)

Converts a (x,y) coordinate in an item position.

=head2 Parameters/Return

 int IupConvertXYToPos(Ihandle *ih, int x, int y); [in C]
 iup.ConvertXYToPos(ih: ihandle, x, y: number) -> (ret: number) [in Lua]

B<ih>: Identifier of the element.

B<x>: X coordinate of the left corner of the interface element.

B<y>: Y coordinate of the upper part of the interface element.

Returns: the position starting at 0 (except for B<IupList> that starts
at 1). If fails returns -1.

=head2 Notes

It can be used for B<IupText> (returns a position in the string),
B<IupList> (returns an item) or B<IupTree> (returns a node identifier).

=head2 See Also

L<IupText|../elem/iuptext.html>, L<IupList|../elem/iuplist.html>,
L<IupTree|../elem/iuptree.html>

=cut