=head1 IupGetLanguage

Returns the language used by some pre-defined dialogs. Returns the same
value as the LANGUAGE global attribute.

=head2 Parameters/Return

 char* IupGetLanguage(void); [in C] iup.GetLanguage() -> (language: string) [in Lua] 

Returns: the language.

=head2 See Also

L<IupSetLanguage|iupsetlanguage.html>,
L<LANGUAGE|../attrib/iup_globals.html#LANGUAGE>.

=cut