=head1 IupGetGlobal

Returns an attribute value from the global environment. The value can
be returned from the driver or from the internal storage.

=head2 Parameters/Return

 char *IupGetGlobal(const char *name); [in C]
 iup.GetGlobal(name: string) -> value: string [in Lua]

B<name>: name of the attribute.

Returns: the attribute value. If the attribute does not exist, NULL
(nil in Lua) is returned.

=head2 Notes

This functionE<rsquo>s return value is not necessarily the same one
used by the application to set the attributeE<rsquo>s value.

The subsequent call to the B<IupGetGlobal> function may change the
contents of the previously returned pointer, as this is an internal IUP
buffer. The user is in charge of storing the value before calling
IupGetGlobal again. This pointer must not be free either.

B<IupGetAttribute> can also be used to get global attributes, just set
the element to NULL.

=head2 See Also

L<IupGetAttribute|iupgetattribute.html>,
L<IupSetGlobal|iupsetglobal.html>

=cut