=head1 IupGetFloat

Returns the value of an interface element attribute as a floating point
number.

=head2 Parameters/Return

 float IupGetFloat(Ihandle *ih, const char *name)  [in C]
 float IupGetFloatId(Ihandle *ih, const char *name, int id)  [in C]
 float IupGetFloatId2(Ihandle* ih, const char* name, int lin, int col)  [in C]
 [There is no equivalent in Lua]

B<ih>: Identifier of the interface element.

B<name>: name of the attribute.

B<id, lin, col>: used when the attribute has additional ids.

Returns: a float corresponding to the attributeE<rsquo>s value.

=head2 See Also

L<IupGetAttribute|iupgetattribute.html>, L<IupGetInt|iupgetint.html>.

=cut