=head1 IupGetAttributes

Returns all attributes of a given element that are in the internal hash
table. The known attributes that are pointers (not strings) are
returned as integers.

The internal attributes are not returned (attributes prefixed with
"_IUP").

Before calling this function the application must ensure that there is
no pointer attributes set for that element, although some known
pointers are handled.

This function should be avoided. Use B<IupGetAllAttributes> instead.

=head2 Parameters/Return

 char* IupGetAttributes (Ihandle *ih); [in C]
 iup.GetAttributes(ih: ihandle) -> (ret: string) [in Lua] 

B<ih>: Identifier of the interface element.

Returns: a string with all attributes in the format: "NAME=VALUE,
NAME="VALUE", ...".

=head2 See Also

L<IupGetAttribute|iupgetattribute.html>,
L<IupGetAllAttributes|iupgetallattributes.html>,
L<IupSetAttribute|iupsetattribute.html>,
L<IupSetAttributes|iupsetattributes.html>,
L<IupStoreAttribute|iupstoreattribute.html>

=cut