=head1 IupGetAllNames

Returns the names of all interface elements that have an associated
name using B<IupSetHandle> or using LED.

=head2 Parameters/Return

 int IupGetAllNames(char** names, int max_n); [in C]
 iup.GetAllNames(max_n: number) -> (names: table, n: number) [in Lua]

B<names>: table receiving the names. Only the list of names need to be
allocated. Each name will point to an internal string.

B<max_n>: maximum number of names the table can receive.

Returns: the number of names loaded to the table. If names==NULL or
max_n==0 then returns the actual number of names.

=head2 Notes

This name is not associated to the name of the Lua variable E<ndash>
this was inherited from LED and is needed for some functions.

=head2 See Also

L<IupSetHandle|iupsethandle.html>, L<IupGetHandle|iupgethandle.html>,
L<IupGetName|iupgetname.html>,
L<IupGetAllDialogs|iupgetalldialogs.html>.

=cut