=head1 IupGetFunction

Returns the function associated to an action when set using
L<IupSetFunction|iupsetfunction.html>.

This function is now deprecated for regular elements, use it only
global callbacks. For regular elements use B<IupGetCallback> instead.

=head2 Parameters/Return

 Icallback IupGetFunction(const char *name); [in C]
 [There is no equivalent in Lua]

B<name>: name of the action.

Returns: the callback or NULL if not found.

=head2 See Also

L<IupSetFunction|iupsetfunction.html>,
L<IupGetCallback|IupGetCallback.html>

=cut