=head1 IupSetClassDefaultAttribute (Since 3.0)

Changes the default value of an attribute for a class. It can be any
attribute, i.e. registered attributes or user custom attributes.

=head2 Parameters/Return

 void IupSetClassDefaultAttribute(const char* classname, const char *name, const char *value); [in C]
 iup.SetClassDefaultAttribute(classname, name, value: string) [in Lua]

B<classname>: name of the class

name: name of the attribute

B<value>: new default value.

=head2 Notes

If the value is DEFAULTFONT, DLGBGCOLOR, DLGFGCOLOR, TXTBGCOLOR,
TXTFGCOLOR or MENUBGCOLOR then the actual default value will be the
global attribute of the same name consulted at the time the attribute
is consulted.

Attributes that are not strings and attributes that have variable
names, like those which has a complementary number, can NOT have a
default value. Some attributes can NOT have a default value by
definition.

If the new default value is (char*)-1, then the default value is set to
be the system default if any is defined.

=head2 See Also

L<IupGetClassName|iupgetclassname.html>,
L<IupGetClassType|iupgetclasstype.html>,
L<IupGetAllAttributes|iupgetallattributes.html>

=cut