=head1 IupSetGlobal

Sets an attribute in the global environment. If the driver process the
attribute then it will not be stored internally.

=head2 Parameters/Return

 void IupSetGlobal(const char *name, const char *value); [in C]
 void IupSetStrGlobal(const char *name, const char *value); [in C]
 iup.SetGlobal(name: string, value: string) [in Lua]

B<name>: name of the attribute.

B<value>: value of the attribute. If it equals NULL (nil in IupLua),
the attribute will be removed.

=head2 Notes

B<IupSetGlobal> can store only constant strings (like "Title", "30",
etc) or application pointers. The given value is not duplicated as a
string, only a reference is stored. Therefore, you can store
application custom attributes, such as a context structure to be used
in a callback.

B<IupSetStrGlobal> (old B<IupStoreGlobal>) can only store strings. The
given string value will be duplicated internally.

L<IupSetAttribute|iupsetattribute.html> functions can also be used to
set global attributes, just set the element to NULL.

=head2 See Also

L<IupGetGlobal|iupgetglobal.html>, L<Global
Attributes|../attrib/iup_globals.html>

=cut