=head1 IupStoreGlobal

Defines an attribute for the global environment but the string is
internally duplicated.

=head2 Parameters/Return

 void IupStoreGlobal(const char *name, const char *value); [in C]
 iup.StoreGlobal(name: string, value: string) [in Lua] 

B<name>: name of the attribute.

B<value>: value of the attribute. If it equals NULL (nil in Lua), the
attribute will be removed.

=head2 Notes

The difference betwwen B<IupSetGlobal> and B<IupStoreGlobal> is the
same of B<IupSetAttribute> and B<IupStoreAttribute>. In the Store
functions the string value is duplicated internally.

The application can also store any private attribute in the global
environment.

B<IupStoreAttribute> can also be used to set global attributes, just
set the element handle to NULL.

=head2 See Also

L<IupStoreAttribute|iupstoreattribute.html>,
L<IupSetAttribute|iupsetattribute.html>,
L<IupGetGlobal|iupgetglobal.html>, L<IupSetGlobal|iupsetglobal.html>

=cut