#!/usr/bin/env perl

package IUP::Internal::Attribute;

use strict;
use warnings;
use Carp;

# xxx TODO xxx optimize accessor generation
sub _get_attr_list { return (qw/
  3STATE             ACCUM_BLUE_SIZE    ACCUM_GREEN_SIZE   ACCUM_RED_SIZE     ACENTER            ACTIVE             ADDCONTROL
  ADDEXPANDED        ADDLEAF            ALIGNMENT          ALLOWNEW           ALPHA              APPEND             APPENDITEM
  AUTOHIDE           AUTOTOGGLE         AXS_XAUTOMAX       AXS_XAUTOMIN       AXS_XAUTOTICK      AXS_XAUTOTICKSIZE  AXS_XCOLOR
  AXS_XCROSSORIGIN   AXS_XFONTSIZE      AXS_XFONTSTYLE     AXS_XLABEL         AXS_XLABELCENTERED AXS_XMAX           AXS_XMIN
  AXS_XREVERSE       AXS_XSCALE         AXS_XTICK          AXS_XTICKDIVISION  AXS_XTICKFONTSIZE  AXS_XTICKFONTSTYLE AXS_XTICKFORMAT
  AXS_XTICKMAJORSIZE AXS_XTICKMAJORSPAN AXS_XTICKSIZE      AXS_YAUTOMAX       AXS_YAUTOMIN       AXS_YAUTOTICK      AXS_YAUTOTICKSIZE
  AXS_YCOLOR         AXS_YCROSSORIGIN   AXS_YFONTSIZE      AXS_YFONTSTYLE     AXS_YLABEL         AXS_YLABELCENTERED AXS_YMAX
  AXS_YMIN           AXS_YREVERSE       AXS_YSCALE         AXS_YTICK          AXS_YTICKDIVISION  AXS_YTICKFONTSIZE  AXS_YTICKFONTSTYLE
  AXS_YTICKFORMAT    AXS_YTICKMAJORSIZE AXS_YTICKMAJORSPAN AXS_YTICKSIZE      BACKGROUND         BACKINGSTORE       BARSIZE
  BGCOLOR            BORDER             BOXED              BPP                BRINGFRONT         BUFFER             BUFFERIZE
  BUTTONDEFAULT      BUTTONRESPONSE     BUTTONS            CANFOCUS           CANVAS             CARET              CARETPOS
  CEL                CGAP               CHANNELS           CHILDCOUNT         CLEAR              CLEARATTRIBUTES    CLIENTSIZE
  CLIENTSIZE1        CLIENTSIZE2        CLIPBOARD          CLIPPED            CLIPRECT           CMARGIN            COLOR
  COLORMAP           COLORTABLE         COMPOSITED         CONTEXT            CONTROL            COUNT              CUEBANNER
  CURRENT            CURSOR             CX                 CY                 DASHED             DEFAULTENTER       DEFAULTESC
  DENSITY            DEPTH              DESIGNMODE         DIALOGFRAME        DIALOGHINT         DIALOGTYPE         DIRECTION
  DIRECTORY          DRAGDROP           DRAWSIZE           DROPDOWN           DROPEXPAND         DS                 DX
  EAST               EDITBOX            ELLIPSIS           EMFAVAILABLE       ERROR              EXPAND             EXPANDCHILDREN
  EXPANDWEIGHT       EXTFILTER          FGCOLOR            FILE               FILEEXIST          FILTER             FILTERINFO
  FILTERUSED         FIRST              FLAT               FLOATING           FOCUSONCLICK       FONT               FORMATTING
  FULL               FULLSCREEN         GAP                GREEN_SIZE         GRID               GRIDCOLOR          GRIDLINESTYLE
  HDC                HEIGHT             HELPBUTTON         HIDEMARK           HIDETASKBAR        HOMOGENEOUS        HOTSPOT
  HSI                HWND               ICON               IMAGE              IMAGEAVAILABLE     IMAGELEAF          IMAGEPOSITION
  IMINACTIVE         IMPORTANT          IMPRESS            IMPRESSBORDER      INSERT             INSERTITE          INVERTED
  IUNKNOWN           KEY                LAYOUTDRAG         LEGENDFONTSIZE     LEGENDFONTSTYLE    LEGENDPOS          LEGENDSHOW
  LIMITSL            MARGIN             MARGINBOTTOM       MARGINLEFT         MARGINRIGHT        MARGINTOP          MARK
  MARKUP             MARQUEE            MASK               MAX                MAXBOX             MAXSIZE            MDIACTIVATE
  MDIACTIVE          MDIARRANGE         MDICHILD           MDICLIENT          MDICLOSEALL        MDIFRAME           MDIMENU
  MDINEXT            MENU               MENUBOX            MIN                MINBOX             MINMAX             MINSIZE
  MODAL              MULTILINE          MULTIPLE           MULTIPLEFILES      NATIVEIMAGE        NATIVEPARENT       NC
  NCGAP              NCMARGIN           NE                 NGAP               NMARGIN            NOCHANGEDIR        NON
  NOOVERWRITEPROMPT  NORMALIZE          NORMALIZERGROUP    NORMALIZESIZE      NORTH              NUM                NW
  OPACITY            ORIENTATION        ORIGIN             OVERWRITE          PADDING            PAGESTEP           PARENTDIALOG
  PASSWORD           PLACEMENT          POSITION           PREVIEW            PREVIEWTEXT        PRIMARY            RADIO
  RASTERSIZE         READONLY           REDRAW             RED_SIZE           REFRESHCONTEXT     REMOVE             REMOVEITEM
  RENAMENODE         REPAINT            RESIZE             RGB                RIGHTBUTTON        RUN                SAVEEMF
  SAVEUNDER          SAVEWMF            SCROLLBAR          SCROLLTO           SCROLLTOPOS        SE                 SECONDARY
  SELECTEDTEXT       SELECTION          SELECTIONPOS       SEPARATOR          SHADOWED           SHAREDCONTEXT      SHOW
  SHOWALPHA          SHOWCOLORTABLE     SHOWDROPDOWN       SHOWGRIP           SHOWHELP           SHOWHEX            SHOWHIDDEN
  SHOWPREVIEW        SHOWTICKS          SHRINK             SIZE               SORT               SOUTH              SPACING
  SPIN               SPINVALUE          SQUARED            STARTFOCUS         STATUS             STENCIL            STEP
  STEREO             SUNKEN             SW                 TABIMAG            TABORIENTATION     TABSIZE            TABTITL
  TABTITLE           TABTYPE            TEXT               TEXTAVAILABLE      TICKSPOS           TIME               TIP
  TITLE              TITLEFONTSIZE      TITLEFONTSTYLE     TITLEIMAGE         TOOLBOX            TOPITEM            TOPMOST
  TRANSPARENCY       TRAY               TRAYIMAGE          TRAYTIP            TYPE               UNIT               VALU
  VALUE              VALUEHEX           VALUEHSI           VALUEPOS           VISIBLE            VISIBLECOLUMNS     VISIBLELINES
  VISUAL             WEST               WID                WIDTH              WMFAVAILABLE       WORDWRAP           X
  XDISPLAY           XWINDOW            Y                  ZORDER
/) };

# global table of available attributes per element (used for generating accessors)
# xxx TODO xxx perhaps delete this hash
my $attrib_table = {
    'IUP::Zbox' => {
         'SIZE' => 1,
         'ALIGNMENT' => 1,
         'VALUEPOS' => 1,
         'EXPAND' => 1,
         'WID' => 1,
         'ACENTER' => 1,
         'NE' => 1,
         'MAXSIZE' => 1,
         'NORTH' => 1,
         'SE' => 1,
         'VALUE' => 1,
         'NW' => 1,
         'FLOATING' => 1,
         'CLIENTSIZE' => 1,
         'FONT' => 1,
         'SOUTH' => 1,
         'POSITION' => 1,
         'SW' => 1,
         'EAST' => 1,
         'WEST' => 1,
         'MINSIZE' => 1
       },
    'IUP::Fill' => {
         'SIZE' => 1,
         'POSITION' => 1,
         'EXPAND' => 1,
         'WID' => 1,
         'FONT' => 1,
         'MINSIZE' => 1,
         'MAXSIZE' => 1
       },
    'IUP::Text' => {
         'NC' => 1,
         'VISIBLE' => 1,
         'Y' => 1,
         'SCROLLTOPOS' => 1,
         'SELECTEDTEXT' => 1,
         'BORDER' => 1,
         'APPEND' => 1,
         'DRAGDROP' => 1,
         'TABSIZE' => 1,
         'SCROLLBAR' => 1,
         'SCROLLTO' => 1,
         'CARETPOS' => 1,
         'VALUE' => 1,
         'RASTERSIZE' => 1,
         'SELECTIONPOS' => 1,
         'VISIBLECOLUMNS' => 1,
         'WORDWRAP' => 1,
         'SPIN' => 1,
         'FONT' => 1,
         'BGCOLOR' => 1,
         'FGCOLOR' => 1,
         'ACTIVE' => 1,
         'MINSIZE' => 1,
         'MASK' => 1,
         'VISIBLELINES' => 1,
         'SELECTION' => 1,
         'SIZE' => 1,
         'ALIGNMENT' => 1,
         'PASSWORD' => 1,
         'CANFOCUS' => 1,
         'SPINVALUE' => 1,
         'PADDING' => 1,
         'MULTILINE' => 1,
         'OVERWRITE' => 1,
         'EXPAND' => 1,
         'FILTER' => 1,
         'WID' => 1,
         'INSERT' => 1,
         'TIP' => 1,
         'MAXSIZE' => 1,
         'ZORDER' => 1,
         'FORMATTING' => 1,
         'X' => 1,
         'CARET' => 1,
         'CLIPBOARD' => 1,
         'READONLY' => 1,
         'POSITION' => 1,
         'CUEBANNER' => 1
       },
    'IUP::List' => {
         'NC' => 1,
         'SHOWDROPDOWN' => 1,
         'VISIBLE' => 1,
         'EDITBOX' => 1,
         'Y' => 1,
         'SCROLLTOPOS' => 1,
         'SELECTEDTEXT' => 1,
         'APPEND' => 1,
          '0' => 1,
          '1' => 1,
          '2' => 1,
          '3' => 1,
          '4' => 1,
          '5' => 1,
          '6' => 1,
          '7' => 1,
          '8' => 1,
          '9' => 1,
          '10' => 1,
          '11' => 1,
          '12' => 1,
          '13' => 1,
          '14' => 1,
          '15' => 1,
          '16' => 1,
         'DRAGDROP' => 1,
         'SORT' => 1,
         'SCROLLBAR' => 1,
         'DROPDOWN' => 1,
         'SCROLLTO' => 1,
         'CARETPOS' => 1,
         'VALUE' => 1,
         'RASTERSIZE' => 1,
         'SELECTIONPOS' => 1,
         'VISIBLECOLUMNS' => 1,
         'FONT' => 1,
         'BGCOLOR' => 1,
         'FGCOLOR' => 1,
         'INSERTITE' => 1,
         'TOPITEM' => 1,
         'ACTIVE' => 1,
         'MINSIZE' => 1,
         'MASK' => 1,
         'SELECTION' => 1,
         'VISIBLELINES' => 1,
         'SIZE' => 1,
         'CANFOCUS' => 1,
         'PADDING' => 1,
         'EXPAND' => 1,
         'FILTER' => 1,
         'WID' => 1,
         'COUNT' => 1,
         'MULTIPLE' => 1,
         'INSERT' => 1,
         'TIP' => 1,
         'MAXSIZE' => 1,
         'REMOVEITEM' => 1,
         'ZORDER' => 1,
         'X' => 1,
         'APPENDITEM' => 1,
         'AUTOHIDE' => 1,
         'SPACING' => 1,
         'CARET' => 1,
         'CLIPBOARD' => 1,
         'READONLY' => 1,
         'POSITION' => 1,
         'CUEBANNER' => 1,
         'DROPEXPAND' => 1
       },
    'IUP::Sbox' => {
         'SIZE' => 1,
         'COLOR' => 1,
         'RASTERSIZE' => 1,
         'CLIENTSIZE' => 1,
         'FONT' => 1,
         'POSITION' => 1,
         'EXPAND' => 1,
         'WID' => 1,
         'MINSIZE' => 1,
         'MAXSIZE' => 1,
         'DIRECTION' => 1
       },
    'IUP::ProgressBar' => {
          'SIZE' => 1,
          'MIN' => 1,
          'ORIENTATION' => 1,
          'MAX' => 1,
          'MARQUEE' => 1,
          'VISIBLE' => 1,
          'Y' => 1,
          'DASHED' => 1,
          'EXPAND' => 1,
          'WID' => 1,
          'TIP' => 1,
          'MAXSIZE' => 1,
          'VALUE' => 1,
          'ZORDER' => 1,
          'RASTERSIZE' => 1,
          'X' => 1,
          'BGCOLOR' => 1,
          'FGCOLOR' => 1,
          'FONT' => 1,
          'POSITION' => 1,
          'ACTIVE' => 1,
          'MINSIZE' => 1
        },
    'IUP::Frame' => {
          'SIZE' => 1,
          'SUNKEN' => 1,
          'VISIBLE' => 1,
          'Y' => 1,
          'EXPAND' => 1,
          'WID' => 1,
          'MAXSIZE' => 1,
	  'MARGIN' => 1,
          'RASTERSIZE' => 1,
          'ZORDER' => 1,
          'X' => 1,
          'CLIENTSIZE' => 1,
          'BGCOLOR' => 1,
          'FGCOLOR' => 1,
          'FONT' => 1,
          'POSITION' => 1,
          'TITLE' => 1,
          'ACTIVE' => 1,
          'MINSIZE' => 1
        },
    'IUP::Cbox' => {
         'SIZE' => 1,
         'CY' => 1,
         'POSITION' => 1,
         'EXPAND' => 1,
         'CLIENTSIZE' => 1,
         'WID' => 1,
         'FONT' => 1,
         'CX' => 1,
         'MINSIZE' => 1,
         'MAXSIZE' => 1
       },
    'IUP::FontDlg' => {
            'COLOR' => 1,
            'VALUE' => 1,
            'TITLE' => 1,
            'PREVIEWTEXT' => 1,
            'STATUS' => 1,
            'PARENTDIALOG' => 1
          },
    'IUP::ColorDlg' => {
             'VALUE' => 1,
             'SHOWHEX' => 1,
             'STATUS' => 1,
             'TITLE' => 1,
             'SHOWHELP' => 1,
             'ALPHA' => 1,
             'PARENTDIALOG' => 1,
             'SHOWALPHA' => 1,
             'VALUEHEX' => 1,
             'VALUEHSI' => 1,
             'SHOWCOLORTABLE' => 1,
             'COLORTABLE' => 1
           },
    'IUP::Canvas' => {
           'SIZE' => 1,
           'XDISPLAY' => 1,
           'CLIPRECT' => 1,
           'CANFOCUS' => 1,
           'VISIBLE' => 1,
           'Y' => 1,
           'DX' => 1,
           'DRAWSIZE' => 1,
           'BORDER' => 1,
           'EXPAND' => 1,
           'DRAGDROP' => 1,
           'HDC' => 1,
           'WID' => 1,
           'SCROLLBAR' => 1,
           'TIP' => 1,
           'XWINDOW' => 1,
           'MAXSIZE' => 1,
           'ZORDER' => 1,
           'RASTERSIZE' => 1,
           'X' => 1,
           'HWND' => 1,
           'FONT' => 1,
           'BGCOLOR' => 1,
           'CURSOR' => 1,
           'POSITION' => 1,
           'ACTIVE' => 1,
           'BACKINGSTORE' => 1,
           'MINSIZE' => 1
         },
    'IUP::Hbox' => {
         'SIZE' => 1,
         'ALIGNMENT' => 1,
         'EXPANDCHILDREN' => 1,
         'NGAP' => 1,
         'EXPANDWEIGHT' => 1,
         'CGAP' => 1,
         'NORMALIZESIZE' => 1,
         'CMARGIN' => 1,
         'EXPAND' => 1,
         'WID' => 1,
         'NCGAP' => 1,
         'MAXSIZE' => 1,
         'FLOATING' => 1,
         'MARGIN' => 1,
         'NMARGIN' => 1,
         'CLIENTSIZE' => 1,
         'FONT' => 1,
         'POSITION' => 1,
         'HOMOGENEOUS' => 1,
         'GAP' => 1,
         'MINSIZE' => 1,
         'NCMARGIN' => 1
       },
    'IUP::GLCanvas' => {
             'COLORMAP' => 1,
             'COLOR' => 1,
             'STENCIL' => 1,
             'STEREO' => 1,
             'SHAREDCONTEXT' => 1,
             'RED_SIZE' => 1,
             'ERROR' => 1,
             'VISUAL' => 1,
             'ACCUM_RED_SIZE' => 1,
             'DEPTH' => 1,
             'ACCUM_BLUE_SIZE' => 1,
             'REFRESHCONTEXT' => 1,
             'GREEN_SIZE' => 1,
             'ALPHA' => 1,
             'CONTEXT' => 1,
             'BUFFER' => 1,
             'ACCUM_GREEN_SIZE' => 1
           },
    'IUP::Dial' => {
         'SIZE' => 1,
         'VISIBLE' => 1,
         'Y' => 1,
         'UNIT' => 1,
         'EXPAND' => 1,
         'WID' => 1,
         'TIP' => 1,
         'MAXSIZE' => 1,
         'DENSITY' => 1,
         'VALUE' => 1,
         'ZORDER' => 1,
         'RASTERSIZE' => 1,
         'X' => 1,
         'FGCOLOR' => 1,
         'TYPE' => 1,
         'BGCOLOR' => 1,
         'FONT' => 1,
         'POSITION' => 1,
         'ACTIVE' => 1,
         'MINSIZE' => 1
       },
    'IUP::Item' => {
         'KEY' => 1,
         'VALUE' => 1,
         'TITLEIMAGE' => 1,
         'AUTOTOGGLE' => 1,
         'IMAGE' => 1,
         'HIDEMARK' => 1,
         'IMPRESS' => 1,
         'TITLE' => 1,
         'ACTIVE' => 1,
         'WID' => 1
       },
    'IUP::Val' => {
        'SIZE' => 1,
        'MIN' => 1,
        'CANFOCUS' => 1,
        'MAX' => 1,
        'VISIBLE' => 1,
        'Y' => 1,
        'INVERTED' => 1,
        'EXPAND' => 1,
        'STEP' => 1,
        'WID' => 1,
        'PAGESTEP' => 1,
        'TIP' => 1,
        'MAXSIZE' => 1,
        'VALUE' => 1,
        'ZORDER' => 1,
        'RASTERSIZE' => 1,
        'SHOWTICKS' => 1,
        'X' => 1,
        'BGCOLOR' => 1,
        'TYPE' => 1,
        'FONT' => 1,
        'POSITION' => 1,
        'ACTIVE' => 1,
        'MINSIZE' => 1,
        'TICKSPOS' => 1
      },
    'IUP::Tabs' => {
         'SIZE' => 1,
         'VISIBLE' => 1,
         'Y' => 1,
         'VALUEPOS' => 1,
         'TABORIENTATION' => 1,
         'TABIMAG' => 1,
         'PADDING' => 1,
         'MULTILINE' => 1,
         'EXPAND' => 1,
         'TABTYPE' => 1,
         'TABTITL' => 1,
         'WID' => 1,
         'MAXSIZE' => 1,
         'VALUE' => 1,
         'ZORDER' => 1,
         'RASTERSIZE' => 1,
         'X' => 1,
         'CLIENTSIZE' => 1,
         'BGCOLOR' => 1,
         'FGCOLOR' => 1,
         'FONT' => 1,
         'POSITION' => 1,
         'ACTIVE' => 1,
         'TABTITLE' => 1,
         'MINSIZE' => 1
       },
    'IUP::Normalizer' => {
         'ADDCONTROL' => 1,
         'NORMALIZE' => 1,
         'NORMALIZERGROUP' => 1
             },
    'IUP::Label' => {
          'SIZE' => 1,
          'ALIGNMENT' => 1,
          'VISIBLE' => 1,
          'Y' => 1,
          'PADDING' => 1,
          'EXPAND' => 1,
          'WID' => 1,
          'TIP' => 1,
          'MAXSIZE' => 1,
          'SEPARATOR' => 1,
          'ZORDER' => 1,
          'RASTERSIZE' => 1,
          'X' => 1,
          'MARKUP' => 1,
          'WORDWRAP' => 1,
          'BGCOLOR' => 1,
          'FGCOLOR' => 1,
          'FONT' => 1,
          'IMAGE' => 1,
          'TITLE' => 1,
	  'TABTITLE' => 1,
          'POSITION' => 1,
          'ACTIVE' => 1,
          'IMINACTIVE' => 1,
          'ELLIPSIS' => 1,
          'MINSIZE' => 1
        },
    'IUP::PPlot' => {
          'VISIBLE' => 1,
          'AXS_YFONTSTYLE' => 1,
          'Y' => 1,
          'AXS_XMAX' => 1,
          'AXS_XREVERSE' => 1,
          'REMOVE' => 1,
          'LEGENDFONTSIZE' => 1,
          'AXS_XFONTSIZE' => 1,
          'MARGINTOP' => 1,
          'AXS_YAUTOMAX' => 1,
          'AXS_XAUTOMIN' => 1,
          'AXS_YTICKFONTSTYLE' => 1,
          'AXS_XTICKFORMAT' => 1,
          'FONT' => 1,
          'BGCOLOR' => 1,
          'AXS_YMIN' => 1,
          'CURRENT' => 1,
          'AXS_YMAX' => 1,
          'TITLE' => 1,
          'ACTIVE' => 1,
          'LEGENDFONTSTYLE' => 1,
          'AXS_YTICKFORMAT' => 1,
          'MINSIZE' => 1,
          'AXS_XCOLOR' => 1,
          'SIZE' => 1,
          'AXS_YAUTOMIN' => 1,
          'AXS_XCROSSORIGIN' => 1,
          'AXS_YREVERSE' => 1,
          'TITLEFONTSIZE' => 1,
          'AXS_XMIN' => 1,
          'AXS_XTICKMAJORSPAN' => 1,
          'AXS_YAUTOTICK' => 1,
          'TIP' => 1,
          'AXS_XAUTOMAX' => 1,
          'MAXSIZE' => 1,
          'AXS_XTICKFONTSTYLE' => 1,
          'ZORDER' => 1,
          'AXS_YTICKSIZE' => 1,
          'AXS_XAUTOTICK' => 1,
          'X' => 1,
          'AXS_YTICK' => 1,
          'LEGENDSHOW' => 1,
          'AXS_XTICKMAJORSIZE' => 1,
          'MARGINRIGHT' => 1,
          'AXS_XLABEL' => 1,
          'TITLEFONTSTYLE' => 1,
          'AXS_YLABEL' => 1,
          'MARGINBOTTOM' => 1,
          'CLEAR' => 1,
          'AXS_XFONTSTYLE' => 1,
          'AXS_XLABELCENTERED' => 1,
          'AXS_XTICKFONTSIZE' => 1,
          'RASTERSIZE' => 1,
          'AXS_XSCALE' => 1,
          'FGCOLOR' => 1,
          'AXS_XTICKSIZE' => 1,
          'GRIDCOLOR' => 1,
          'AXS_YFONTSIZE' => 1,
          'AXS_YLABELCENTERED' => 1,
          'AXS_YCROSSORIGIN' => 1,
          'AXS_YTICKMAJORSIZE' => 1,
          'AXS_XTICKDIVISION' => 1,
          'AXS_YAUTOTICKSIZE' => 1,
          'WID' => 1,
          'GRID' => 1,
          'COUNT' => 1,
          'AXS_YCOLOR' => 1,
          'AXS_YTICKFONTSIZE' => 1,
          'REDRAW' => 1,
          'AXS_XTICK' => 1,
          'AXS_YSCALE' => 1,
          'AXS_XAUTOTICKSIZE' => 1,
          'DS' => 1,
          'AXS_YTICKDIVISION' => 1,
          'GRIDLINESTYLE' => 1,
          'POSITION' => 1,
          'LEGENDPOS' => 1,
          'AXS_YTICKMAJORSPAN' => 1,
          'MARGINLEFT' => 1
        },
    'IUP::Clipboard' => {
        'TEXTAVAILABLE' => 1,
        'WMFAVAILABLE' => 1,
        'SAVEEMF' => 1,
        'IMAGEAVAILABLE' => 1,
        'NATIVEIMAGE' => 1,
        'IMAGE' => 1,
        'EMFAVAILABLE' => 1,
        'TEXT' => 1,
        'SAVEWMF' => 1
            },
    'IUP::OleControl' => {
         'SIZE' => 1,
         'ZORDER' => 1,
         'RASTERSIZE' => 1,
         'DESIGNMODE' => 1,
         'X' => 1,
         'VISIBLE' => 1,
         'IUNKNOWN' => 1,
         'Y' => 1,
         'POSITION' => 1,
         'ACTIVE' => 1,
         'WID' => 1,
         'MINSIZE' => 1,
         'TIP' => 1,
         'MAXSIZE' => 1
             },
    'IUP::Submenu' => {
            'KEY' => 1,
            'TITLE' => 1,
            'ACTIVE' => 1,
            'WID' => 1,
            'IMAGE' => 1
          },
    'IUP::Tree' => {
         'RENAMENODE' => 1,
         'ADDLEAF' => 1,
         'MARK' => 1,
         'ADDEXPANDED' => 1,
         'VALU' => 1,
         'IMAGELEAF' => 1,
         'CHILDCOUNT' => 1
       },
    'IUP::Button' => {
           'SIZE' => 1,
           'ALIGNMENT' => 1,
           'CANFOCUS' => 1,
           'FOCUSONCLICK' => 1,
           'VISIBLE' => 1,
           'Y' => 1,
           'IMPRESSBORDER' => 1,
           'PADDING' => 1,
           'IMPRESS' => 1,
           'EXPAND' => 1,
           'WID' => 1,
           'IMAGEPOSITION' => 1,
           'TIP' => 1,
           'MAXSIZE' => 1,
           'ZORDER' => 1,
           'RASTERSIZE' => 1,
           'X' => 1,
           'MARKUP' => 1,
           'SPACING' => 1,
           'BGCOLOR' => 1,
           'FGCOLOR' => 1,
           'FONT' => 1,
           'IMAGE' => 1,
           'FLAT' => 1,
           'POSITION' => 1,
           'TITLE' => 1,
           'ACTIVE' => 1,
           'IMINACTIVE' => 1,
           'MINSIZE' => 1
         },
    'IUP::Colorbar' => {
             'SIZE' => 1,
             'PREVIEW' => 1,
             'ORIENTATION' => 1,
             'VISIBLE' => 1,
             'Y' => 1,
             'NUM' => 1,
             'SQUARED' => 1,
             'EXPAND' => 1,
             'WID' => 1,
             'PRIMARY' => 1,
             'CEL' => 1,
             'TIP' => 1,
             'MAXSIZE' => 1,
             'SECONDARY' => 1,
             'SHOW' => 1,
             'ZORDER' => 1,
             'RASTERSIZE' => 1,
             'X' => 1,
             'BUFFERIZE' => 1,
             'BGCOLOR' => 1,
             'FONT' => 1,
             'TRANSPARENCY' => 1,
             'POSITION' => 1,
             'SHADOWED' => 1,
             'ACTIVE' => 1,
             'MINSIZE' => 1
           },
    'IUP::MessageDlg' => {
         'VALUE' => 1,
         'TITLE' => 1,
         'DIALOGTYPE' => 1,
         'BUTTONS' => 1,
         'PARENTDIALOG' => 1,
         'BUTTONRESPONSE' => 1,
         'BUTTONDEFAULT' => 1
             },
    'IUP::FileDlg' => {
            'FILE' => 1,
            'MULTIPLEFILES' => 1,
            'STATUS' => 1,
            'NOCHANGEDIR' => 1,
            'FILTERUSED' => 1,
            'FILTER' => 1,
            'PARENTDIALOG' => 1,
            'DIRECTORY' => 1,
            'VALUE' => 1,
            'ALLOWNEW' => 1,
            'EXTFILTER' => 1,
            'DIALOGTYPE' => 1,
            'SHOWPREVIEW' => 1,
            'FILEEXIST' => 1,
            'NOOVERWRITEPROMPT' => 1,
            'TITLE' => 1,
            'SHOWHIDDEN' => 1,
            'FILTERINFO' => 1
          },
    'IUP::Image' => {
          'HEIGHT' => 1,
          'WIDTH' => 1,
          'RASTERSIZE' => 1,
          'CHANNELS' => 1,
          'HOTSPOT' => 1,
          'BGCOLOR' => 1,
          '0' => 1,
          '1' => 1,
          '2' => 1,
          '3' => 1,
          '4' => 1,
          '5' => 1,
          '6' => 1,
          '7' => 1,
          '8' => 1,
          '9' => 1,
          '10' => 1,
          '11' => 1,
          '12' => 1,
          '13' => 1,
          '14' => 1,
          '15' => 1,
          '16' => 1,
          'WID' => 1,
          'BPP' => 1
        },
    'IUP::ColorBrowser' => {
           'SIZE' => 1,
           'VISIBLE' => 1,
           'Y' => 1,
           'EXPAND' => 1,
           'WID' => 1,
           'RGB' => 1,
           'HSI' => 1,
           'TIP' => 1,
           'MAXSIZE' => 1,
           'RASTERSIZE' => 1,
           'ZORDER' => 1,
           'X' => 1,
           'BGCOLOR' => 1,
           'FONT' => 1,
           'POSITION' => 1,
           'ACTIVE' => 1,
           'MINSIZE' => 1
         },
    'IUP::Cells' => {
          'SIZE' => 1,
          'CLIPPED' => 1,
          'VISIBLE' => 1,
          'Y' => 1,
          'FULL' => 1,
          'NON' => 1,
          'LIMITSL' => 1,
          'WID' => 1,
          'SCROLLBAR' => 1,
          'TIP' => 1,
          'MAXSIZE' => 1,
          'ZORDER' => 1,
          'RASTERSIZE' => 1,
          'X' => 1,
          'REPAINT' => 1,
          'BUFFERIZE' => 1,
          'BGCOLOR' => 1,
          'FONT' => 1,
          'IMAGE' => 1,
          'POSITION' => 1,
          'ORIGIN' => 1,
          'FIRST' => 1,
          'ACTIVE' => 1,
          'BOXED' => 1,
          'CANVAS' => 1,
          'MINSIZE' => 1
        },
    'IUP::Menu' => {
         'RADIO' => 1,
         'WID' => 1,
         'BGCOLOR' => 1
       },
    'IUP::Toggle' => {
           'SIZE' => 1,
           'ALIGNMENT' => 1,
           'CANFOCUS' => 1,
           'VISIBLE' => 1,
           'Y' => 1,
           'PADDING' => 1,
           'RADIO' => 1,
           'IMPRESS' => 1,
           'EXPAND' => 1,
           'WID' => 1,
           'TIP' => 1,
           'MAXSIZE' => 1,
           'VALUE' => 1,
           'ZORDER' => 1,
           'RASTERSIZE' => 1,
           'X' => 1,
           'MARKUP' => 1,
           'BGCOLOR' => 1,
           'FGCOLOR' => 1,
           'FONT' => 1,
           '3STATE' => 1,
           'IMAGE' => 1,
           'RIGHTBUTTON' => 1,
           'POSITION' => 1,
           'TITLE' => 1,
           'ACTIVE' => 1,
           'IMINACTIVE' => 1,
           'MINSIZE' => 1
         },
    'IUP::Timer' => {
          'RUN' => 1,
          'TIME' => 1,
          'WID' => 1
        },
    'IUP::Vbox' => {
         'SIZE' => 1,
         'ALIGNMENT' => 1,
         'EXPANDCHILDREN' => 1,
         'NGAP' => 1,
         'EXPANDWEIGHT' => 1,
         'CGAP' => 1,
         'NORMALIZESIZE' => 1,
         'CMARGIN' => 1,
         'EXPAND' => 1,
         'WID' => 1,
         'NCGAP' => 1,
         'MAXSIZE' => 1,
         'FLOATING' => 1,
         'MARGIN' => 1,
         'NMARGIN' => 1,
         'CLIENTSIZE' => 1,
         'FONT' => 1,
         'POSITION' => 1,
         'HOMOGENEOUS' => 1,
         'GAP' => 1,
         'MINSIZE' => 1,
         'NCMARGIN' => 1
       },
    'IUP::Dialog' => {
           'MDINEXT' => 1,
           'MDIACTIVATE' => 1,
           'BRINGFRONT' => 1,
           'MDIARRANGE' => 1,
           'MENUBOX' => 1,
           'NATIVEPARENT' => 1,
           'VISIBLE' => 1,
           'Y' => 1,
           'BORDER' => 1,
           'OPACITY' => 1,
           'MDICHILD' => 1,
           'DRAGDROP' => 1,
           'MDIFRAME' => 1,
           'STARTFOCUS' => 1,
           'DIALOGHINT' => 1,
           'XWINDOW' => 1,
           'MAXBOX' => 1,
           'DIALOGFRAME' => 1,
           'RASTERSIZE' => 1,
           'MODAL' => 1,
           'HWND' => 1,
           'CLIENTSIZE' => 1,
           'TOOLBOX' => 1,
           'BGCOLOR' => 1,
           'FONT' => 1,
           'DEFAULTENTER' => 1,
           'TRAYTIP' => 1,
           'CONTROL' => 1,
           'FULLSCREEN' => 1,
           'TITLE' => 1,
           'ACTIVE' => 1,
           'MINSIZE' => 1,
           'SIZE' => 1,
           'TRAY' => 1,
           'SHRINK' => 1,
           'HIDETASKBAR' => 1,
           'MINBOX' => 1,
           'MDIMENU' => 1,
           'COMPOSITED' => 1,
           'SAVEUNDER' => 1,
           'BACKGROUND' => 1,
           'ICON' => 1,
           'EXPAND' => 1,
           'MDICLOSEALL' => 1,
           'PARENTDIALOG' => 1,
           'WID' => 1,
           'TIP' => 1,
           'MENU' => 1,
           'MAXSIZE' => 1,
           'HELPBUTTON' => 1,
           'TOPMOST' => 1,
           'ZORDER' => 1,
           'X' => 1,
           'RESIZE' => 1,
           'CURSOR' => 1,
           'PLACEMENT' => 1,
           'IMPORTANT' => 1,
           'MDICLIENT' => 1,
           'TRAYIMAGE' => 1,
           'MDIACTIVE' => 1,
           'DEFAULTESC' => 1
         },
    'IUP::Radio' => {
          'VALUE' => 1,
          'CLIENTSIZE' => 1,
          'VISIBLE' => 1,
          'FONT' => 1,
          'POSITION' => 1,
          'EXPAND' => 1,
          'WID' => 1,
          'MINSIZE' => 1,
          'MAXSIZE' => 1
        },
    'IUP::Split' => {
          'SIZE' => 1,
          'COLOR' => 1,
          'SHOWGRIP' => 1,
          'MINMAX' => 1,
          'EXPAND' => 1,
          'LAYOUTDRAG' => 1,
          'WID' => 1,
          'BARSIZE' => 1,
          'MAXSIZE' => 1,
          'CLIENTSIZE2' => 1,
          'VALUE' => 1,
          'RASTERSIZE' => 1,
          'AUTOHIDE' => 1,
          'FONT' => 1,
          'POSITION' => 1,
          'CLIENTSIZE1' => 1,
          'MINSIZE' => 1,
          'DIRECTION' => 1
        },
    'IUP::User' => {
         'CLEARATTRIBUTES' => 1
       },
    'IUP::Gauge' => {
          'SIZE' => 1,
          'MIN' => 1,
          'MAX' => 1,
          'VISIBLE' => 1,
          'Y' => 1,
          'DASHED' => 1,
          'PADDING' => 1,
          'TEXT' => 1,
          'EXPAND' => 1,
          'WID' => 1,
          'TIP' => 1,
          'MAXSIZE' => 1,
          'SHOW' => 1,
          'VALUE' => 1,
          'ZORDER' => 1,
          'RASTERSIZE' => 1,
          'X' => 1,
          'FGCOLOR' => 1,
          'BGCOLOR' => 1,
          'FONT' => 1,
          'POSITION' => 1,
          'ACTIVE' => 1,
          'MINSIZE' => 1
        }
};

sub _get_attr_listXXX {
  my $pkg = shift;
  my $h = $attrib_table->{$pkg};
  return () unless defined($h);
  return keys %$h;
}

sub _is_attr_valid {
  my ($pkg, $name) = @_;
  #my $h = $attrib_table->{$pkg};
  #return 0 unless defined($h);
  #return defined($h->{$name}) ? 1 : 0;
  carp "Warning: DO NOT USE _is_attr_valid!";
  return 1;
}

1;

__END__

=head1 NAME

IUP::Internal::Attribute - Perl extension for IUP xxx

=cut
