#!/usr/bin/env perl

# BEWARE: this is a generated file, DO NOT EDIT THIS FILE MANUALLY!!!

package IUP::Internal::Attribute;

use strict;
use warnings;
use Carp;

# global table of available attributes per element (used for generating accessors)
my $attrib_table = {
  'IUP::Button' => {
    ALIGNMENT => 'NO_INHERIT',                                # src=yes doc=yes
    BACKGROUND => 'DEFAULT',                                  # src=yes doc=no
    BGCOLOR => 'DEFAULT',                                     # src=yes doc=yes
    FGCOLOR => 'DEFAULT',                                     # src=yes doc=yes
    FLAT => 'DEFAULT',                                        # src=yes doc=yes
    FOCUSONCLICK => 'NO_INHERIT',                             # src=yes doc=yes
    IMAGE => 'NO_DEFAULTVALUE|NO_INHERIT',                    # src=yes doc=yes
    IMAGEPOSITION => 'NOT_MAPPED|NO_INHERIT',                 # src=yes doc=yes
    IMINACTIVE => 'NO_DEFAULTVALUE|NO_INHERIT',               # src=yes doc=yes
    IMPRESS => 'NO_DEFAULTVALUE|NO_INHERIT',                  # src=yes doc=yes
    IMPRESSBORDER => 'NO_INHERIT',                            # src=yes doc=yes
    MARKUP => 'DEFAULT',                                      # src=yes doc=yes
    PADDING => 'NOT_MAPPED',                                  # src=yes doc=yes
    SPACING => 'NOT_MAPPED|NO_INHERIT',                       # src=yes doc=yes
    TITLE => 'NO_DEFAULTVALUE|NO_INHERIT',                    # src=yes doc=yes
  },
  'IUP::Canvas' => {
    BACKINGSTORE => 'NOT_MAPPED',                             # src=yes doc=yes
    BGCOLOR => 'DEFAULT',                                     # src=yes doc=yes
    BORDER => 'DEFAULT',                                      # src=yes doc=yes
    CLIPRECT => 'unknown',                                    # src=no doc=yes
    CURSOR => 'NO_INHERIT',                                   # src=yes doc=yes
    DRAGDROP => 'NO_INHERIT',                                 # src=yes doc=yes
    DRAWABLE => 'NO_STRING',                                  # src=yes doc=no
    DRAWSIZE => 'READONLY|NO_INHERIT',                        # src=yes doc=yes
    DX => 'NO_INHERIT',                                       # src=yes doc=yes
    DY => 'NO_INHERIT',                                       # src=yes doc=no
    HDC_WMPAINT => 'unknown',                                 # src=no doc=yes
    HWND => 'NO_STRING|NO_INHERIT',                           # src=yes doc=yes
    LINEX => 'NOT_MAPPED|NO_INHERIT',                         # src=yes doc=no
    LINEY => 'NOT_MAPPED|NO_INHERIT',                         # src=yes doc=no
    POSX => 'NO_INHERIT',                                     # src=yes doc=no
    POSY => 'NO_INHERIT',                                     # src=yes doc=no
    SCROLLBAR => 'NO_INHERIT',                                # src=yes doc=yes
    XAUTOHIDE => 'NOT_MAPPED',                                # src=yes doc=no
    XDISPLAY => 'READONLY|NOT_MAPPED|NO_INHERIT|NO_STRING',   # src=yes doc=yes
    XMAX => 'NOT_MAPPED|NO_INHERIT',                          # src=yes doc=no
    XMIN => 'NOT_MAPPED|NO_INHERIT',                          # src=yes doc=no
    XSCREEN => 'READONLY|NOT_MAPPED|NO_INHERIT|NO_STRING',    # src=yes doc=no
    XWINDOW => 'NO_INHERIT|NO_STRING',                        # src=yes doc=yes
    YAUTOHIDE => 'NOT_MAPPED',                                # src=yes doc=no
    YMAX => 'NOT_MAPPED|NO_INHERIT',                          # src=yes doc=no
    YMIN => 'NOT_MAPPED|NO_INHERIT',                          # src=yes doc=no
  },
  'IUP::Cells' => {
    BGCOLOR => 'NO_INHERIT',                                  # src=yes doc=yes
    BOXED => 'NOT_MAPPED',                                    # src=yes doc=yes
    BUFFERIZE => 'DEFAULT',                                   # src=yes doc=yes
    CANVAS => 'NO_STRING|READONLY|NO_INHERIT',                # src=yes doc=yes
    CLIPPED => 'NOT_MAPPED',                                  # src=yes doc=yes
    FIRST_COL => 'READONLY|NO_INHERIT',                       # src=yes doc=yes
    FIRST_LINE => 'READONLY|NO_INHERIT',                      # src=yes doc=yes
    FULL_VISIBLE => 'NO_INHERIT',                             # src=yes doc=yes
    IMAGE_CANVAS => 'NO_STRING|READONLY|NO_INHERIT',          # src=yes doc=yes
    LIMITS => 'READONLY|NO_INHERIT',                          # src=yes doc=no
    NON_SCROLLABLE_COLS => 'NOT_MAPPED',                      # src=yes doc=yes
    NON_SCROLLABLE_LINES => 'NOT_MAPPED',                     # src=yes doc=yes
    NO_COLOR => 'NO_INHERIT',                                 # src=yes doc=no
    ORIGIN => 'DEFAULT',                                      # src=yes doc=yes
    REPAINT => 'WRITEONLY|NO_INHERIT',                        # src=yes doc=yes
    SCROLLBAR => 'unknown',                                   # src=no doc=yes
  },
  'IUP::Clipboard' => {
    EMFAVAILABLE => 'READONLY|NOT_MAPPED|NO_INHERIT',         # src=yes doc=yes
    IMAGE => 'WRITEONLY|NOT_MAPPED|NO_INHERIT',               # src=yes doc=yes
    IMAGEAVAILABLE => 'READONLY|NOT_MAPPED|NO_INHERIT',       # src=yes doc=yes
    NATIVEIMAGE => 'NO_STRING|NOT_MAPPED|NO_INHERIT',         # src=yes doc=yes
    SAVEEMF => 'WRITEONLY|NOT_MAPPED|NO_INHERIT',             # src=yes doc=yes
    SAVEWMF => 'WRITEONLY|NOT_MAPPED|NO_INHERIT',             # src=yes doc=yes
    TEXT => 'NOT_MAPPED|NO_INHERIT',                          # src=yes doc=yes
    TEXTAVAILABLE => 'READONLY|NOT_MAPPED|NO_INHERIT',        # src=yes doc=yes
    WMFAVAILABLE => 'READONLY|NOT_MAPPED|NO_INHERIT',         # src=yes doc=yes
  },
  'IUP::ColorBar' => {
    BGCOLOR => 'NO_INHERIT',                                  # src=yes doc=yes
    BUFFERIZE => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=yes
    CELL => 'NOT_MAPPED|NO_INHERIT',                          # src=yes doc=no
    NUM_CELLS => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=yes
    NUM_PARTS => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=yes
    ORIENTATION => 'NOT_MAPPED',                              # src=yes doc=yes
    PREVIEW_SIZE => 'NOT_MAPPED|NO_INHERIT',                  # src=yes doc=yes
    PRIMARY_CELL => 'NOT_MAPPED|NO_INHERIT',                  # src=yes doc=yes
    SECONDARY_CELL => 'NOT_MAPPED|NO_INHERIT',                # src=yes doc=yes
    SHADOWED => 'NOT_MAPPED',                                 # src=yes doc=yes
    SHOW_PREVIEW => 'NOT_MAPPED',                             # src=yes doc=yes
    SHOW_SECONDARY => 'NOT_MAPPED',                           # src=yes doc=yes
    SQUARED => 'NOT_MAPPED',                                  # src=yes doc=yes
    TRANSPARENCY => 'NOT_MAPPED',                             # src=yes doc=yes
  },
  'IUP::ColorBrowser' => {
    BGCOLOR => 'NO_INHERIT',                                  # src=yes doc=yes
    HSI => 'NOT_MAPPED|NO_INHERIT',                           # src=yes doc=yes
    RGB => 'NOT_MAPPED|NO_INHERIT',                           # src=yes doc=yes
  },
  'IUP::ColorDlg' => {
    ALPHA => 'NOT_MAPPED|NO_INHERIT',                         # src=yes doc=yes
    COLORTABLE => 'NOT_MAPPED|NO_INHERIT',                    # src=yes doc=yes
    SHOWALPHA => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=yes
    SHOWCOLORTABLE => 'NOT_MAPPED|NO_INHERIT',                # src=yes doc=yes
    SHOWHELP => 'NOT_MAPPED|NO_INHERIT',                      # src=yes doc=yes
    SHOWHEX => 'NOT_MAPPED|NO_INHERIT',                       # src=yes doc=yes
    STATUS => 'READONLY|NOT_MAPPED|NO_INHERIT',               # src=yes doc=yes
    VALUE => 'NOT_MAPPED|NO_INHERIT',                         # src=yes doc=yes
    VALUEHEX => 'NOT_MAPPED|NO_INHERIT',                      # src=yes doc=yes
    VALUEHSI => 'NOT_MAPPED|NO_INHERIT',                      # src=yes doc=yes
  },
  'IUP::Dial' => {
    BGCOLOR => 'NO_INHERIT',                                  # src=yes doc=yes
    DENSITY => 'NOT_MAPPED',                                  # src=yes doc=yes
    FGCOLOR => 'NOT_MAPPED',                                  # src=yes doc=yes
    TYPE => 'NOT_MAPPED|NO_INHERIT',                          # src=yes doc=yes
    UNIT => 'NOT_MAPPED',                                     # src=yes doc=yes
    VALUE => 'NO_DEFAULTVALUE|NOT_MAPPED|NO_INHERIT',         # src=yes doc=yes
  },
  'IUP::FileDlg' => {
    ALLOWNEW => 'NO_INHERIT',                                 # src=yes doc=yes
    DIALOGTYPE => 'NO_INHERIT',                               # src=yes doc=yes
    DIRECTORY => 'NO_INHERIT',                                # src=yes doc=yes
    EXTFILTER => 'NO_INHERIT',                                # src=yes doc=yes
    FILE => 'NO_INHERIT',                                     # src=yes doc=yes
    FILEEXIST => 'NO_INHERIT|READONLY',                       # src=yes doc=yes
    FILTER => 'NO_INHERIT',                                   # src=yes doc=yes
    FILTERINFO => 'NO_INHERIT',                               # src=yes doc=yes
    FILTERUSED => 'NO_INHERIT',                               # src=yes doc=yes
    MULTIPLEFILES => 'NO_INHERIT',                            # src=yes doc=yes
    NOCHANGEDIR => 'NO_INHERIT',                              # src=yes doc=yes
    NOOVERWRITEPROMPT => 'NO_INHERIT',                        # src=yes doc=yes
    PREVIEWDC => 'NO_INHERIT|READONLY|NO_STRING',             # src=yes doc=no
    PREVIEWHEIGHT => 'NO_INHERIT|READONLY|NO_STRING',         # src=yes doc=no
    PREVIEWWIDTH => 'NO_INHERIT|READONLY|NO_STRING',          # src=yes doc=no
    SHOWHIDDEN => 'NO_INHERIT',                               # src=yes doc=yes
    SHOWPREVIEW => 'NO_INHERIT',                              # src=yes doc=yes
    STATUS => 'NO_INHERIT|READONLY',                          # src=yes doc=yes
    VALUE => 'NO_INHERIT|READONLY',                           # src=yes doc=yes
  },
  'IUP::FontDlg' => {
    COLOR => 'NO_INHERIT',                                    # src=yes doc=yes
    PREVIEWTEXT => 'NO_INHERIT',                              # src=yes doc=yes
    STATUS => 'NO_INHERIT|READONLY',                          # src=yes doc=yes
    VALUE => 'NO_INHERIT',                                    # src=yes doc=yes
  },
  'IUP::Frame' => {
    BACKGROUND => 'DEFAULT',                                  # src=yes doc=no
    BGCOLOR => 'DEFAULT',                                     # src=yes doc=yes
    CLIENTSIZE => 'READONLY|NO_INHERIT',                      # src=yes doc=yes
    FGCOLOR => 'DEFAULT',                                     # src=yes doc=yes
    SUNKEN => 'NO_INHERIT',                                   # src=yes doc=yes
    TITLE => 'NO_DEFAULTVALUE|NO_INHERIT',                    # src=yes doc=yes
  },
  'IUP::GLCanvas' => {
    ACCUM_ALPHA_SIZE => 'unknown',                            # src=no doc=yes
    ACCUM_BLUE_SIZE => 'unknown',                             # src=no doc=yes
    ACCUM_GREEN_SIZE => 'unknown',                            # src=no doc=yes
    ACCUM_RED_SIZE => 'unknown',                              # src=no doc=yes
    ALPHA_SIZE => 'unknown',                                  # src=no doc=yes
    BLUE_SIZE => 'unknown',                                   # src=no doc=yes
    BUFFER => 'DEFAULT',                                      # src=yes doc=yes
    BUFFER_SIZE => 'unknown',                                 # src=no doc=yes
    COLOR => 'DEFAULT',                                       # src=yes doc=yes
    COLORMAP => 'READONLY|NO_STRING',                         # src=yes doc=yes
    CONTEXT => 'READONLY|NO_STRING',                          # src=yes doc=yes
    DEPTH_SIZE => 'unknown',                                  # src=no doc=yes
    ERROR => 'unknown',                                       # src=no doc=yes
    GREEN_SIZE => 'unknown',                                  # src=no doc=yes
    RED_SIZE => 'unknown',                                    # src=no doc=yes
    REFRESHCONTEXT => 'WRITEONLY|NO_INHERIT',                 # src=yes doc=yes
    SHAREDCONTEXT => 'unknown',                               # src=no doc=yes
    STENCIL_SIZE => 'unknown',                                # src=no doc=yes
    STEREO => 'unknown',                                      # src=no doc=yes
    VISUAL => 'READONLY|NO_STRING|NOT_MAPPED',                # src=yes doc=yes
  },
  'IUP::Gauge' => {
    BGCOLOR => 'NO_INHERIT',                                  # src=yes doc=yes
    DASHED => 'NOT_MAPPED',                                   # src=yes doc=yes
    FGCOLOR => 'NOT_MAPPED',                                  # src=yes doc=yes
    MAX => 'NOT_MAPPED|NO_INHERIT',                           # src=yes doc=yes
    MIN => 'NOT_MAPPED|NO_INHERIT',                           # src=yes doc=yes
    PADDING => 'NOT_MAPPED',                                  # src=yes doc=yes
    SHOW_TEXT => 'NOT_MAPPED',                                # src=yes doc=yes
    TEXT => 'NOT_MAPPED|NO_INHERIT',                          # src=yes doc=yes
    VALUE => 'NOT_MAPPED|NO_INHERIT',                         # src=yes doc=yes
  },
  'IUP::Hbox' => {
    ALIGNMENT => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=yes
  },
  'IUP::Image' => {
    BGCOLOR => 'NOT_MAPPED|NO_INHERIT',                       # src=yes doc=yes
    BPP => 'READONLY|NOT_MAPPED|NO_INHERIT',                  # src=yes doc=yes
    CHANNELS => 'READONLY|NOT_MAPPED|NO_INHERIT',             # src=yes doc=yes
    HEIGHT => 'READONLY|NOT_MAPPED|NO_INHERIT',               # src=yes doc=yes
    HOTSPOT => 'NOT_MAPPED|NO_INHERIT',                       # src=yes doc=yes
    WIDTH => 'READONLY|NOT_MAPPED|NO_INHERIT',                # src=yes doc=yes
  },
  'IUP::Item' => {
    AUTOTOGGLE => 'NOT_MAPPED|NO_INHERIT',                    # src=yes doc=yes
    HIDEMARK => 'unknown',                                    # src=no doc=yes
    IMAGE => 'unknown',                                       # src=no doc=yes
    IMPRESS => 'unknown',                                     # src=no doc=yes
    KEY => 'NOT_MAPPED|NO_INHERIT',                           # src=yes doc=yes
    TITLE => 'unknown',                                       # src=no doc=yes
    TITLEIMAGE => 'unknown',                                  # src=no doc=yes
    VALUE => 'unknown',                                       # src=no doc=yes
  },
  'IUP::Label' => {
    ALIGNMENT => 'NO_INHERIT',                                # src=yes doc=yes
    BACKGROUND => 'DEFAULT',                                  # src=yes doc=no
    BGCOLOR => 'DEFAULT',                                     # src=yes doc=yes
    ELLIPSIS => 'DEFAULT',                                    # src=yes doc=yes
    FGCOLOR => 'DEFAULT',                                     # src=yes doc=yes
    IMAGE => 'NO_DEFAULTVALUE|NO_INHERIT',                    # src=yes doc=yes
    IMINACTIVE => 'NO_DEFAULTVALUE|NO_INHERIT',               # src=yes doc=yes
    MARKUP => 'DEFAULT',                                      # src=yes doc=yes
    PADDING => 'NOT_MAPPED',                                  # src=yes doc=yes
    PANGOLAYOUT => 'NO_INHERIT',                              # src=yes doc=no
    SEPARATOR => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=yes
    TITLE => 'NO_DEFAULTVALUE|NO_INHERIT',                    # src=yes doc=yes
    WORDWRAP => 'DEFAULT',                                    # src=yes doc=yes
  },
  'IUP::List' => {
    APPEND => 'WRITEONLY|NO_INHERIT',                         # src=yes doc=yes
    APPENDITEM => 'NOT_MAPPED|NO_INHERIT',                    # src=yes doc=yes
    AUTOHIDE => 'NO_INHERIT',                                 # src=yes doc=yes
    BGCOLOR => 'DEFAULT',                                     # src=yes doc=yes
    CARET => 'NO_INHERIT',                                    # src=yes doc=yes
    CARETPOS => 'NO_INHERIT',                                 # src=yes doc=yes
    CLIPBOARD => 'NO_INHERIT',                                # src=yes doc=yes
    COUNT => 'READONLY|NOT_MAPPED|NO_INHERIT',                # src=yes doc=yes
    CUEBANNER => 'NO_INHERIT',                                # src=yes doc=yes
    DRAGDROP => 'NO_INHERIT',                                 # src=yes doc=yes
    DROPDOWN => 'NOT_MAPPED|NO_INHERIT',                      # src=yes doc=yes
    DROPEXPAND => 'NO_INHERIT',                               # src=yes doc=yes
    EDITBOX => 'NOT_MAPPED|NO_INHERIT',                       # src=yes doc=yes
    FGCOLOR => 'DEFAULT',                                     # src=yes doc=yes
    FILTER => 'NO_INHERIT',                                   # src=yes doc=yes
    IDVALUE => 'NO_INHERIT',                                  # src=yes doc=no
    INSERT => 'WRITEONLY|NO_INHERIT',                         # src=yes doc=yes
    INSERTITE => 'unknown',                                   # src=no doc=yes
    INSERTITEM => 'NOT_MAPPED|NO_INHERIT',                    # src=yes doc=no
    MASK => 'NOT_MAPPED|NO_INHERIT',                          # src=yes doc=yes
    MASKCASEI => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=no
    MASKFLOAT => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=no
    MASKINT => 'NOT_MAPPED|NO_INHERIT',                       # src=yes doc=no
    MULTIPLE => 'NOT_MAPPED|NO_INHERIT',                      # src=yes doc=yes
    NC => 'NOT_MAPPED',                                       # src=yes doc=yes
    OLD_MASK_DATA => 'READONLY|NOT_MAPPED|NO_INHERIT',        # src=yes doc=no
    PADDING => 'NOT_MAPPED',                                  # src=yes doc=yes
    READONLY => 'DEFAULT',                                    # src=yes doc=yes
    REMOVEITEM => 'NOT_MAPPED|NO_INHERIT',                    # src=yes doc=yes
    SCROLLBAR => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=yes
    SCROLLTO => 'WRITEONLY|NO_INHERIT',                       # src=yes doc=yes
    SCROLLTOPOS => 'WRITEONLY|NO_INHERIT',                    # src=yes doc=yes
    SELECTEDTEXT => 'NO_INHERIT',                             # src=yes doc=yes
    SELECTION => 'NO_INHERIT',                                # src=yes doc=yes
    SELECTIONPOS => 'NO_INHERIT',                             # src=yes doc=yes
    SHOWDROPDOWN => 'WRITEONLY|NO_INHERIT',                   # src=yes doc=yes
    SORT => 'unknown',                                        # src=no doc=yes
    SPACING => 'NOT_MAPPED',                                  # src=yes doc=yes
    TOPITEM => 'NO_INHERIT',                                  # src=yes doc=yes
    VALUE => 'NO_DEFAULTVALUE|NO_INHERIT',                    # src=yes doc=yes
    VISIBLECOLUMNS => 'NOT_MAPPED|NO_INHERIT',                # src=yes doc=yes
    VISIBLELINES => 'NOT_MAPPED|NO_INHERIT',                  # src=yes doc=yes
    VISIBLE_ITEMS => 'DEFAULT',                               # src=yes doc=yes
  },
  'IUP::Matrix' => {
    ADDCOL => 'NOT_MAPPED|WRITEONLY|NO_INHERIT',              # src=yes doc=no
    ADDLIN => 'NOT_MAPPED|WRITEONLY|NO_INHERIT',              # src=yes doc=no
    ALIGNMENT => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=no
    AREA => 'NOT_MAPPED|NO_INHERIT',                          # src=yes doc=no
    BGCOLOR => 'NOT_MAPPED',                                  # src=yes doc=no
    CARET => 'NOT_MAPPED|NO_INHERIT',                         # src=yes doc=no
    DELCOL => 'NOT_MAPPED|WRITEONLY|NO_INHERIT',              # src=yes doc=no
    DELLIN => 'NOT_MAPPED|WRITEONLY|NO_INHERIT',              # src=yes doc=no
    EDIT_MODE => 'NO_INHERIT',                                # src=yes doc=no
    FGCOLOR => 'NOT_MAPPED',                                  # src=yes doc=no
    FOCUS_CELL => 'NOT_MAPPED|NO_INHERIT',                    # src=yes doc=no
    FRAMECOLOR => 'NO_INHERIT',                               # src=yes doc=no
    FRAMEHORIZCOLOR => 'NOT_MAPPED',                          # src=yes doc=no
    FRAMEVERTCOLOR => 'NOT_MAPPED',                           # src=yes doc=no
    HEIGHT => 'NOT_MAPPED|NO_INHERIT',                        # src=yes doc=no
    HEIGHTDEF => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=no
    HIDDENTEXTMARKS => 'NOT_MAPPED|NO_INHERIT',               # src=yes doc=no
    HIDEFOCUS => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=no
    IDVALUE => 'NO_INHERIT',                                  # src=yes doc=no
    MARK => 'NO_INHERIT',                                     # src=yes doc=no
    MARKAREA => 'NOT_MAPPED|NO_INHERIT',                      # src=yes doc=no
    MARKED => 'NO_INHERIT',                                   # src=yes doc=no
    MARKMODE => 'NOT_MAPPED|NO_INHERIT',                      # src=yes doc=no
    MARKMULTIPLE => 'NOT_MAPPED|NO_INHERIT',                  # src=yes doc=no
    MARK_MODE => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=no
    MASK => 'NOT_MAPPED|NO_INHERIT',                          # src=yes doc=no
    MULTILINE => 'NO_INHERIT',                                # src=yes doc=no
    MULTIPLE => 'NOT_MAPPED|NO_INHERIT',                      # src=yes doc=no
    NUMCOL => 'NOT_MAPPED|NO_INHERIT',                        # src=yes doc=no
    NUMCOL_VISIBLE => 'NOT_MAPPED|NO_INHERIT',                # src=yes doc=no
    NUMCOL_VISIBLE_LAST => 'NOT_MAPPED|NO_INHERIT',           # src=yes doc=no
    NUMLIN => 'NOT_MAPPED|NO_INHERIT',                        # src=yes doc=no
    NUMLIN_VISIBLE => 'NOT_MAPPED|NO_INHERIT',                # src=yes doc=no
    NUMLIN_VISIBLE_LAST => 'NOT_MAPPED|NO_INHERIT',           # src=yes doc=no
    OLD_MASK_DATA => 'NO_STRING|READONLY|NOT_MAPPED|NO_INHERIT', # src=yes doc=no
    ORIGIN => 'NO_INHERIT',                                   # src=yes doc=no
    RASTERHEIGHT => 'NOT_MAPPED|NO_INHERIT',                  # src=yes doc=no
    RASTERWIDTH => 'NOT_MAPPED|NO_INHERIT',                   # src=yes doc=no
    READONLY => 'NOT_MAPPED|NO_INHERIT',                      # src=yes doc=no
    REDRAW => 'WRITEONLY|NO_INHERIT',                         # src=yes doc=no
    RESIZEMATRIX => 'NOT_MAPPED|NO_INHERIT',                  # src=yes doc=no
    SELECTION => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=no
    SHOW => 'WRITEONLY|NO_INHERIT',                           # src=yes doc=no
    SORTSIGN => 'NOT_MAPPED|NO_INHERIT',                      # src=yes doc=no
    USETITLESIZE => 'NOT_MAPPED|NO_INHERIT',                  # src=yes doc=no
    VALUE => 'NO_DEFAULTVALUE|NO_INHERIT',                    # src=yes doc=no
    WIDTH => 'NOT_MAPPED|NO_INHERIT',                         # src=yes doc=no
    WIDTHDEF => 'NOT_MAPPED|NO_INHERIT',                      # src=yes doc=no
  },
  'IUP::Menu' => {
    BGCOLOR => 'DEFAULT',                                     # src=yes doc=yes
    FLAT_ALPHA => 'NOT_MAPPED|NO_INHERIT',                    # src=yes doc=no
    HIDEMARK => 'NOT_MAPPED',                                 # src=yes doc=no
    IMAGE => 'NO_DEFAULTVALUE|NO_INHERIT',                    # src=yes doc=no
    IMPRESS => 'NO_DEFAULTVALUE|NO_INHERIT',                  # src=yes doc=no
    RADIO => 'NOT_MAPPED|NO_INHERIT',                         # src=yes doc=yes
    TITLE => 'NO_DEFAULTVALUE|NO_INHERIT',                    # src=yes doc=no
    TITLEIMAGE => 'NO_DEFAULTVALUE|NO_INHERIT',               # src=yes doc=no
    VALUE => 'NO_DEFAULTVALUE|NO_INHERIT',                    # src=yes doc=no
  },
  'IUP::MessageDlg' => {
    BUTTONDEFAULT => 'NO_INHERIT',                            # src=yes doc=yes
    BUTTONRESPONSE => 'NO_INHERIT',                           # src=yes doc=yes
    BUTTONS => 'NO_INHERIT',                                  # src=yes doc=yes
    DIALOGTYPE => 'NO_INHERIT',                               # src=yes doc=yes
    VALUE => 'unknown',                                       # src=no doc=yes
  },
  'IUP::Normalizer' => {
    ADDCONTROL => 'NOT_MAPPED|NO_INHERIT',                    # src=yes doc=yes
    ADDCONTROL_HANDLE => 'NOT_MAPPED|NO_INHERIT',             # src=yes doc=yes
    NORMALIZE => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=yes
  },
  'IUP::OleControl' => {
    BGCOLOR => 'NOT_MAPPED',                                  # src=yes doc=no
    DESIGNMODE => 'NOT_MAPPED|NO_INHERIT',                    # src=yes doc=yes
    DESIGNMODE_DONT_NOTIFY => 'NOT_MAPPED|NO_INHERIT',        # src=yes doc=yes
    IUNKNOWN => 'READONLY|NOT_MAPPED|NO_INHERIT|NO_STRING',   # src=yes doc=yes
  },
  'IUP::PPlot' => {
    AXS_XAUTOMAX => 'NOT_MAPPED|NO_INHERIT',                  # src=yes doc=yes
    AXS_XAUTOMIN => 'NOT_MAPPED|NO_INHERIT',                  # src=yes doc=yes
    AXS_XAUTOTICK => 'NOT_MAPPED|NO_INHERIT',                 # src=yes doc=yes
    AXS_XAUTOTICKSIZE => 'NOT_MAPPED|NO_INHERIT',             # src=yes doc=yes
    AXS_XCOLOR => 'NOT_MAPPED|NO_INHERIT',                    # src=yes doc=yes
    AXS_XCROSSORIGIN => 'NOT_MAPPED|NO_INHERIT',              # src=yes doc=yes
    AXS_XFONTSIZE => 'NOT_MAPPED|NO_INHERIT',                 # src=yes doc=yes
    AXS_XFONTSTYLE => 'NOT_MAPPED|NO_INHERIT',                # src=yes doc=yes
    AXS_XLABEL => 'NOT_MAPPED|NO_INHERIT',                    # src=yes doc=yes
    AXS_XLABELCENTERED => 'NOT_MAPPED|NO_INHERIT',            # src=yes doc=yes
    AXS_XMAX => 'NOT_MAPPED|NO_INHERIT',                      # src=yes doc=yes
    AXS_XMIN => 'NOT_MAPPED|NO_INHERIT',                      # src=yes doc=yes
    AXS_XREVERSE => 'NOT_MAPPED|NO_INHERIT',                  # src=yes doc=yes
    AXS_XSCALE => 'NOT_MAPPED|NO_INHERIT',                    # src=yes doc=yes
    AXS_XTICK => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=yes
    AXS_XTICKDIVISION => 'NOT_MAPPED|NO_INHERIT',             # src=yes doc=yes
    AXS_XTICKFONTSIZE => 'NOT_MAPPED|NO_INHERIT',             # src=yes doc=yes
    AXS_XTICKFONTSTYLE => 'NOT_MAPPED|NO_INHERIT',            # src=yes doc=yes
    AXS_XTICKFORMAT => 'NOT_MAPPED|NO_INHERIT',               # src=yes doc=yes
    AXS_XTICKMAJORSIZE => 'NOT_MAPPED|NO_INHERIT',            # src=yes doc=yes
    AXS_XTICKMAJORSPAN => 'NOT_MAPPED|NO_INHERIT',            # src=yes doc=yes
    AXS_XTICKSIZE => 'NOT_MAPPED|NO_INHERIT',                 # src=yes doc=yes
    AXS_YAUTOMAX => 'NOT_MAPPED|NO_INHERIT',                  # src=yes doc=yes
    AXS_YAUTOMIN => 'NOT_MAPPED|NO_INHERIT',                  # src=yes doc=yes
    AXS_YAUTOTICK => 'NOT_MAPPED|NO_INHERIT',                 # src=yes doc=yes
    AXS_YAUTOTICKSIZE => 'NOT_MAPPED|NO_INHERIT',             # src=yes doc=yes
    AXS_YCOLOR => 'NOT_MAPPED|NO_INHERIT',                    # src=yes doc=yes
    AXS_YCROSSORIGIN => 'NOT_MAPPED|NO_INHERIT',              # src=yes doc=yes
    AXS_YFONTSIZE => 'NOT_MAPPED|NO_INHERIT',                 # src=yes doc=yes
    AXS_YFONTSTYLE => 'NOT_MAPPED|NO_INHERIT',                # src=yes doc=yes
    AXS_YLABEL => 'NOT_MAPPED|NO_INHERIT',                    # src=yes doc=yes
    AXS_YLABELCENTERED => 'NOT_MAPPED|NO_INHERIT',            # src=yes doc=yes
    AXS_YMAX => 'NOT_MAPPED|NO_INHERIT',                      # src=yes doc=yes
    AXS_YMIN => 'NOT_MAPPED|NO_INHERIT',                      # src=yes doc=yes
    AXS_YREVERSE => 'NOT_MAPPED|NO_INHERIT',                  # src=yes doc=yes
    AXS_YSCALE => 'NOT_MAPPED|NO_INHERIT',                    # src=yes doc=yes
    AXS_YTICK => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=yes
    AXS_YTICKDIVISION => 'NOT_MAPPED|NO_INHERIT',             # src=yes doc=yes
    AXS_YTICKFONTSIZE => 'NOT_MAPPED|NO_INHERIT',             # src=yes doc=yes
    AXS_YTICKFONTSTYLE => 'NOT_MAPPED|NO_INHERIT',            # src=yes doc=yes
    AXS_YTICKFORMAT => 'NOT_MAPPED|NO_INHERIT',               # src=yes doc=yes
    AXS_YTICKMAJORSIZE => 'NOT_MAPPED|NO_INHERIT',            # src=yes doc=yes
    AXS_YTICKMAJORSPAN => 'NOT_MAPPED|NO_INHERIT',            # src=yes doc=yes
    AXS_YTICKSIZE => 'NOT_MAPPED|NO_INHERIT',                 # src=yes doc=yes
    BGCOLOR => 'NOT_MAPPED',                                  # src=yes doc=yes
    CLEAR => 'WRITEONLY|NOT_MAPPED|NO_INHERIT',               # src=yes doc=yes
    COUNT => 'READONLY|NOT_MAPPED|NO_INHERIT',                # src=yes doc=yes
    CURRENT => 'NOT_MAPPED|NO_INHERIT',                       # src=yes doc=yes
    DS_COLOR => 'NOT_MAPPED|NO_INHERIT',                      # src=yes doc=yes
    DS_EDIT => 'NOT_MAPPED|NO_INHERIT',                       # src=yes doc=yes
    DS_LEGEND => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=yes
    DS_LINESTYLE => 'NOT_MAPPED|NO_INHERIT',                  # src=yes doc=yes
    DS_LINEWIDTH => 'NOT_MAPPED|NO_INHERIT',                  # src=yes doc=yes
    DS_MARKSIZE => 'NOT_MAPPED|NO_INHERIT',                   # src=yes doc=yes
    DS_MARKSTYLE => 'NOT_MAPPED|NO_INHERIT',                  # src=yes doc=yes
    DS_MODE => 'NOT_MAPPED|NO_INHERIT',                       # src=yes doc=yes
    DS_REMOVE => 'WRITEONLY|NOT_MAPPED|NO_INHERIT',           # src=yes doc=yes
    DS_SHOWVALUES => 'NOT_MAPPED|NO_INHERIT',                 # src=yes doc=yes
    FGCOLOR => 'NOT_MAPPED',                                  # src=yes doc=yes
    GRID => 'NOT_MAPPED|NO_INHERIT',                          # src=yes doc=yes
    GRIDCOLOR => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=yes
    GRIDLINESTYLE => 'NOT_MAPPED|NO_INHERIT',                 # src=yes doc=yes
    LEGENDFONTSIZE => 'NOT_MAPPED|NO_INHERIT',                # src=yes doc=yes
    LEGENDFONTSTYLE => 'NOT_MAPPED|NO_INHERIT',               # src=yes doc=yes
    LEGENDPOS => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=yes
    LEGENDSHOW => 'NOT_MAPPED|NO_INHERIT',                    # src=yes doc=yes
    MARGINBOTTOM => 'NOT_MAPPED|NO_INHERIT',                  # src=yes doc=yes
    MARGINLEFT => 'NOT_MAPPED|NO_INHERIT',                    # src=yes doc=yes
    MARGINRIGHT => 'NOT_MAPPED|NO_INHERIT',                   # src=yes doc=yes
    MARGINTOP => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=yes
    REDRAW => 'WRITEONLY|NO_INHERIT',                         # src=yes doc=yes
    REMOVE => 'WRITEONLY|NOT_MAPPED|NO_INHERIT',              # src=yes doc=yes
    TITLE => 'NOT_MAPPED|NO_INHERIT',                         # src=yes doc=yes
    TITLEFONTSIZE => 'NOT_MAPPED|NO_INHERIT',                 # src=yes doc=yes
    TITLEFONTSTYLE => 'NOT_MAPPED|NO_INHERIT',                # src=yes doc=yes
  },
  'IUP::ProgressBar' => {
    BGCOLOR => 'DEFAULT',                                     # src=yes doc=yes
    DASHED => 'NO_INHERIT',                                   # src=yes doc=yes
    FGCOLOR => 'DEFAULT',                                     # src=yes doc=yes
    MARQUEE => 'NO_INHERIT',                                  # src=yes doc=yes
    MAX => 'NOT_MAPPED|NO_INHERIT',                           # src=yes doc=yes
    MIN => 'NOT_MAPPED|NO_INHERIT',                           # src=yes doc=yes
    ORIENTATION => 'NO_INHERIT',                              # src=yes doc=yes
    VALUE => 'NO_DEFAULTVALUE|NO_INHERIT',                    # src=yes doc=yes
  },
  'IUP::Radio' => {
    CLIENTSIZE => 'READONLY|NOT_MAPPED|NO_INHERIT',           # src=yes doc=yes
    VALUE => 'NOT_MAPPED|NO_INHERIT',                         # src=yes doc=yes
    VALUE_HANDLE => 'NOT_MAPPED|NO_INHERIT|NO_STRING',        # src=yes doc=yes
  },
  'IUP::Sbox' => {
    CLIENTSIZE => 'READONLY|NO_INHERIT',                      # src=yes doc=yes
    COLOR => 'NOT_MAPPED|NO_INHERIT',                         # src=yes doc=yes
    DIRECTION => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=yes
  },
  'IUP::Split' => {
    AUTOHIDE => 'NOT_MAPPED|NO_INHERIT',                      # src=yes doc=yes
    BARSIZE => 'NOT_MAPPED|NO_INHERIT',                       # src=yes doc=yes
    CLIENTSIZE1 => 'READONLY|NO_INHERIT',                     # src=yes doc=yes
    CLIENTSIZE2 => 'READONLY|NO_INHERIT',                     # src=yes doc=yes
    COLOR => 'NO_INHERIT',                                    # src=yes doc=yes
    DIRECTION => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=yes
    LAYOUTDRAG => 'NOT_MAPPED|NO_INHERIT',                    # src=yes doc=yes
    MINMAX => 'NOT_MAPPED|NO_INHERIT',                        # src=yes doc=yes
    SHOWGRIP => 'NOT_MAPPED|NO_INHERIT',                      # src=yes doc=yes
    VALUE => 'NOT_MAPPED|NO_INHERIT',                         # src=yes doc=yes
  },
  'IUP::Submenu' => {
    IMAGE => 'unknown',                                       # src=no doc=yes
    KEY => 'NOT_MAPPED|NO_INHERIT',                           # src=yes doc=yes
    TITLE => 'unknown',                                       # src=no doc=yes
  },
  'IUP::Tabs' => {
    ALIGNMENT => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=no
    BACKGROUND => 'DEFAULT',                                  # src=yes doc=no
    BGCOLOR => 'DEFAULT',                                     # src=yes doc=yes
    CLIENTSIZE => 'NO_DEFAULTVALUE|READONLY|NOT_MAPPED|NO_INHERIT', # src=yes doc=yes
    FGCOLOR => 'NOT_MAPPED',                                  # src=yes doc=yes
    FLAT_ALPHA => 'NOT_MAPPED|NO_INHERIT',                    # src=yes doc=no
    FONT_ACTIVE => 'NOT_MAPPED|NO_INHERIT',                   # src=yes doc=no
    FONT_INACTIVE => 'NOT_MAPPED|NO_INHERIT',                 # src=yes doc=no
    MULTILINE => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=yes
    PADDING => 'NOT_MAPPED|NO_INHERIT',                       # src=yes doc=yes
    REPAINT => 'WRITEONLY|NOT_MAPPED|NO_INHERIT',             # src=yes doc=no
    TABIMAGE => 'NO_INHERIT',                                 # src=yes doc=no
    TABORIENTATION => 'NOT_MAPPED|NO_INHERIT',                # src=yes doc=yes
    TABSIZE => 'NO_DEFAULTVALUE|NOT_MAPPED|NO_INHERIT',       # src=yes doc=no
    TABTITLE => 'NO_DEFAULTVALUE|NOT_MAPPED|NO_INHERIT',      # src=yes doc=yes
    TABTYPE => 'NOT_MAPPED|NO_INHERIT',                       # src=yes doc=yes
    VALUE => 'NO_DEFAULTVALUE|NOT_MAPPED|NO_INHERIT',         # src=yes doc=yes
    VALUEPOS => 'NO_DEFAULTVALUE|NOT_MAPPED|NO_INHERIT',      # src=yes doc=yes
    VALUE_HANDLE => 'NOT_MAPPED|NO_INHERIT|NO_STRING',        # src=yes doc=yes
  },
  'IUP::Text' => {
    ADDFORMATTAG => 'NOT_MAPPED|NO_INHERIT',                  # src=yes doc=no
    ADDFORMATTAG_HANDLE => 'NOT_MAPPED|NO_INHERIT',           # src=yes doc=no
    ALIGNMENT => 'NO_INHERIT',                                # src=yes doc=yes
    APPEND => 'NOT_MAPPED|WRITEONLY|NO_INHERIT',              # src=yes doc=yes
    APPENDNEWLINE => 'NOT_MAPPED|NO_INHERIT',                 # src=yes doc=no
    BGCOLOR => 'DEFAULT',                                     # src=yes doc=yes
    BORDER => 'NO_INHERIT',                                   # src=yes doc=yes
    CARET => 'NO_INHERIT',                                    # src=yes doc=yes
    CARETPOS => 'NO_INHERIT',                                 # src=yes doc=yes
    CLIPBOARD => 'NO_INHERIT',                                # src=yes doc=yes
    CUEBANNER => 'NO_INHERIT',                                # src=yes doc=yes
    DRAGDROP => 'NO_INHERIT',                                 # src=yes doc=yes
    FGCOLOR => 'DEFAULT',                                     # src=yes doc=yes
    FILTER => 'NO_INHERIT',                                   # src=yes doc=yes
    FORMATTING => 'READONLY|NOT_MAPPED|NO_INHERIT',           # src=yes doc=yes
    INSERT => 'NOT_MAPPED|WRITEONLY|NO_INHERIT',              # src=yes doc=yes
    MASK => 'NOT_MAPPED|NO_INHERIT',                          # src=yes doc=yes
    MASKCASEI => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=no
    MASKFLOAT => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=no
    MASKINT => 'NOT_MAPPED|NO_INHERIT',                       # src=yes doc=no
    MULTILINE => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=yes
    NC => 'NOT_MAPPED',                                       # src=yes doc=yes
    OLD_MASK_DATA => 'READONLY|NOT_MAPPED|NO_INHERIT',        # src=yes doc=no
    OVERWRITE => 'NO_INHERIT',                                # src=yes doc=yes
    PADDING => 'NOT_MAPPED',                                  # src=yes doc=yes
    PANGOLAYOUT => 'NO_INHERIT',                              # src=yes doc=no
    PASSWORD => 'NO_INHERIT',                                 # src=yes doc=yes
    READONLY => 'DEFAULT',                                    # src=yes doc=yes
    REMOVEFORMATTING => 'WRITEONLY|NO_INHERIT',               # src=yes doc=no
    SCROLLBAR => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=yes
    SCROLLTO => 'WRITEONLY|NO_INHERIT',                       # src=yes doc=yes
    SCROLLTOPOS => 'WRITEONLY|NO_INHERIT',                    # src=yes doc=yes
    SELECTEDTEXT => 'NO_INHERIT',                             # src=yes doc=yes
    SELECTION => 'NO_INHERIT',                                # src=yes doc=yes
    SELECTIONPOS => 'NO_INHERIT',                             # src=yes doc=yes
    SPIN => 'NO_INHERIT',                                     # src=yes doc=yes
    SPINALIGN => 'NO_INHERIT',                                # src=yes doc=no
    SPINAUTO => 'NO_INHERIT',                                 # src=yes doc=no
    SPININC => 'NO_INHERIT',                                  # src=yes doc=no
    SPINMAX => 'NO_INHERIT',                                  # src=yes doc=no
    SPINMIN => 'NO_INHERIT',                                  # src=yes doc=no
    SPINVALUE => 'NO_INHERIT',                                # src=yes doc=yes
    SPINWRAP => 'NO_INHERIT',                                 # src=yes doc=no
    TABSIZE => 'DEFAULT',                                     # src=yes doc=yes
    VALUE => 'NO_DEFAULTVALUE|NO_INHERIT',                    # src=yes doc=yes
    VISIBLECOLUMNS => 'NO_INHERIT',                           # src=yes doc=yes
    VISIBLELINES => 'NO_INHERIT',                             # src=yes doc=yes
    WORDWRAP => 'DEFAULT',                                    # src=yes doc=yes
  },
  'IUP::Timer' => {
    RUN => 'NOT_MAPPED|NO_INHERIT',                           # src=yes doc=yes
    TIME => 'NOT_MAPPED|NO_INHERIT',                          # src=yes doc=yes
  },
  'IUP::Toggle' => {
    ALIGNMENT => 'NO_INHERIT',                                # src=yes doc=yes
    BACKGROUND => 'DEFAULT',                                  # src=yes doc=no
    BGCOLOR => 'DEFAULT',                                     # src=yes doc=yes
    FGCOLOR => 'DEFAULT',                                     # src=yes doc=yes
    FLAT_ALPHA => 'NOT_MAPPED|NO_INHERIT',                    # src=yes doc=no
    IMAGE => 'NO_DEFAULTVALUE|NO_INHERIT',                    # src=yes doc=yes
    IMINACTIVE => 'NO_DEFAULTVALUE|NO_INHERIT',               # src=yes doc=yes
    IMPRESS => 'NO_DEFAULTVALUE|NO_INHERIT',                  # src=yes doc=yes
    MARKUP => 'DEFAULT',                                      # src=yes doc=yes
    PADDING => 'NOT_MAPPED',                                  # src=yes doc=yes
    RADIO => 'READONLY|NO_INHERIT',                           # src=yes doc=yes
    RIGHTBUTTON => 'NO_INHERIT',                              # src=yes doc=yes
    SELECTCOLOR => 'NO_INHERIT',                              # src=yes doc=no
    TITLE => 'NO_DEFAULTVALUE|NO_INHERIT',                    # src=yes doc=yes
    VALUE => 'NO_DEFAULTVALUE|NO_INHERIT',                    # src=yes doc=yes
  },
  'IUP::Tree' => {
    ADDBRANCH => 'NOT_MAPPED|WRITEONLY|NO_INHERIT',           # src=yes doc=no
    ADDEXPANDED => 'NOT_MAPPED|NO_INHERIT',                   # src=yes doc=yes
    ADDLEAF => 'NOT_MAPPED|WRITEONLY|NO_INHERIT',             # src=yes doc=yes
    ADDROOT => 'NO_INHERIT',                                  # src=yes doc=no
    BGCOLOR => 'DEFAULT',                                     # src=yes doc=no
    CHILDCOUNT => 'READONLY|NO_INHERIT',                      # src=yes doc=yes
    COLOR => 'NO_INHERIT',                                    # src=yes doc=no
    COPYNODE => 'NOT_MAPPED|WRITEONLY|NO_INHERIT',            # src=yes doc=no
    COUNT => 'NO_DEFAULTVALUE|READONLY|NO_INHERIT',           # src=yes doc=no
    CTRL => 'NOT_MAPPED',                                     # src=yes doc=no
    DELNODE => 'NOT_MAPPED|WRITEONLY|NO_INHERIT',             # src=yes doc=no
    DEPTH => 'READONLY|NO_DEFAULTVALUE|NO_INHERIT',           # src=yes doc=no
    DRAGDROP => 'NO_INHERIT',                                 # src=yes doc=no
    EXPANDALL => 'WRITEONLY||NO_INHERIT',                     # src=yes doc=no
    FGCOLOR => 'DEFAULT',                                     # src=yes doc=no
    FINDUSERDATA => 'READONLY|NO_INHERIT',                    # src=yes doc=no
    FLAT_ALPHA => 'NOT_MAPPED|NO_INHERIT',                    # src=yes doc=no
    IMAGE => 'WRITEONLY|NO_INHERIT',                          # src=yes doc=no
    IMAGEBRANCHCOLLAPSED => 'NO_INHERIT',                     # src=yes doc=no
    IMAGEBRANCHEXPANDED => 'NO_INHERIT',                      # src=yes doc=no
    IMAGEEXPANDED => 'WRITEONLY|NO_INHERIT',                  # src=yes doc=no
    IMAGELEAF => 'NO_INHERIT',                                # src=yes doc=yes
    INDENTATION => 'DEFAULT',                                 # src=yes doc=no
    INSERTBRANCH => 'NOT_MAPPED|WRITEONLY|NO_INHERIT',        # src=yes doc=no
    INSERTLEAF => 'NOT_MAPPED|WRITEONLY|NO_INHERIT',          # src=yes doc=no
    KIND => 'READONLY|NO_INHERIT',                            # src=yes doc=no
    LASTADDNODE => 'READONLY|NO_INHERIT',                     # src=yes doc=no
    MARK => 'WRITEONLY|NO_INHERIT',                           # src=yes doc=yes
    MARKED => 'NO_INHERIT',                                   # src=yes doc=no
    MARKEDNODES => 'NO_DEFAULTVALUE|NO_INHERIT',              # src=yes doc=no
    MARKMODE => 'NOT_MAPPED',                                 # src=yes doc=no
    MARKSTART => 'NO_DEFAULTVALUE|NO_INHERIT',                # src=yes doc=no
    MOVENODE => 'NOT_MAPPED|WRITEONLY|NO_INHERIT',            # src=yes doc=no
    PARENT => 'READONLY|NO_INHERIT',                          # src=yes doc=no
    RENAME => 'WRITEONLY|NO_INHERIT',                         # src=yes doc=no
    RENAMENODE => 'unknown',                                  # src=no doc=yes
    RUBBERBAND => 'NO_INHERIT',                               # src=yes doc=no
    SHIFT => 'NOT_MAPPED',                                    # src=yes doc=no
    SHOWDRAGDROP => 'NOT_MAPPED|NO_INHERIT',                  # src=yes doc=no
    SHOWRENAME => 'NOT_MAPPED|NO_INHERIT',                    # src=yes doc=no
    SPACING => 'NOT_MAPPED',                                  # src=yes doc=no
    STARTING => 'NO_DEFAULTVALUE|NO_INHERIT',                 # src=yes doc=no
    STATE => 'NO_DEFAULTVALUE|NO_INHERIT',                    # src=yes doc=no
    TITLE => 'NO_INHERIT',                                    # src=yes doc=no
    TITLEFONT => 'NO_INHERIT',                                # src=yes doc=no
    TOPITEM => 'WRITEONLY|NO_INHERIT',                        # src=yes doc=no
    TOTALCHILDCOUNT => 'READONLY|NO_INHERIT',                 # src=yes doc=no
    USERDATA => 'NO_STRING|NO_INHERIT',                       # src=yes doc=no
    VALUE => 'NO_DEFAULTVALUE|NO_INHERIT',                    # src=yes doc=no
  },
  'IUP::User' => {
    CLEARATTRIBUTES => 'NOT_MAPPED|NO_INHERIT',               # src=yes doc=yes
  },
  'IUP::Val' => {
    BACKGROUND => 'DEFAULT',                                  # src=yes doc=no
    BGCOLOR => 'NO_INHERIT',                                  # src=yes doc=yes
    HANDLER_IMAGE => 'NO_DEFAULTVALUE|NOT_MAPPED',            # src=yes doc=no
    HANDLER_IMAGE_INACTIVE => 'NO_DEFAULTVALUE|NOT_MAPPED',   # src=yes doc=no
    INVERTED => 'NOT_MAPPED|NO_INHERIT',                      # src=yes doc=yes
    MAX => 'NOT_MAPPED',                                      # src=yes doc=yes
    MIN => 'NOT_MAPPED',                                      # src=yes doc=yes
    PAGESTEP => 'NOT_MAPPED',                                 # src=yes doc=yes
    SHOWTICKS => 'NOT_MAPPED',                                # src=yes doc=yes
    STEP => 'NOT_MAPPED',                                     # src=yes doc=yes
    TICKSPOS => 'NOT_MAPPED',                                 # src=yes doc=yes
    TYPE => 'NOT_MAPPED|NO_INHERIT',                          # src=yes doc=yes
    VALUE => 'NO_DEFAULTVALUE|NOT_MAPPED|NO_INHERIT',         # src=yes doc=yes
  },
  'IUP::Vbox' => {
    ALIGNMENT => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=yes
  },
  'IUP::Zbox' => {
    ALIGNMENT => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=yes
    VALUE => 'NOT_MAPPED|NO_INHERIT',                         # src=yes doc=yes
    VALUEPOS => 'NOT_MAPPED|NO_INHERIT',                      # src=yes doc=yes
    VALUE_HANDLE => 'NOT_MAPPED|NO_INHERIT|NO_STRING',        # src=yes doc=yes
  },
  '_base' => {
    ACTIVE => 'DEFAULT',                                      # src=yes doc=no
    CANFOCUS => 'NO_INHERIT',                                 # src=yes doc=no
    CHARSIZE => 'NO_DEFAULTVALUE|READONLY|NOT_MAPPED|NO_INHERIT', # src=yes doc=no
    CX => 'unknown',                                          # src=no doc=no
    CY => 'unknown',                                          # src=no doc=no
    ENTERWINDOW_CB => 'NO_INHERIT',                           # src=yes doc=no
    EXPAND => 'NOT_MAPPED|NO_INHERIT',                        # src=yes doc=no
    EXPANDWEIGHT => 'NOT_MAPPED|NO_INHERIT',                  # src=yes doc=no
    FLOATING => 'NOT_MAPPED|NO_INHERIT',                      # src=yes doc=no
    FONT => 'NOT_MAPPED|NO_INHERIT',                          # src=yes doc=no
    FONTFACE => 'READONLY|NOT_MAPPED|NO_INHERIT',             # src=yes doc=no
    FONTSIZE => 'NOT_MAPPED|NO_INHERIT',                      # src=yes doc=no
    FONTSTYLE => 'NOT_MAPPED|NO_INHERIT',                     # src=yes doc=no
    GETFOCUS_CB => 'NO_INHERIT',                              # src=yes doc=no
    HELP_CB => 'NO_INHERIT',                                  # src=yes doc=no
    HFONT => 'NOT_MAPPED|NO_INHERIT|NO_STRING',               # src=yes doc=no
    KILLFOCUS_CB => 'NO_INHERIT',                             # src=yes doc=no
    K_ANY => 'NO_INHERIT',                                    # src=yes doc=no
    LEAVEWINDOW_CB => 'NO_INHERIT',                           # src=yes doc=no
    MAP_CB => 'NO_INHERIT',                                   # src=yes doc=no
    MAXSIZE => 'NOT_MAPPED|NO_INHERIT',                       # src=yes doc=no
    MINSIZE => 'NOT_MAPPED|NO_INHERIT',                       # src=yes doc=no
    NAME => 'NO_DEFAULTVALUE|NOT_MAPPED|NO_INHERIT',          # src=yes doc=no
    NORMALIZERGROUP => 'NOT_MAPPED|NO_INHERIT',               # src=yes doc=no
    PANGOFONTDESC => 'NOT_MAPPED|NO_INHERIT|NO_STRING',       # src=yes doc=no
    POSITION => 'NO_DEFAULTVALUE|NOT_MAPPED|NO_INHERIT',      # src=yes doc=no
    RASTERSIZE => 'NO_DEFAULTVALUE|NOT_MAPPED|NO_INHERIT',    # src=yes doc=no
    SIZE => 'NO_DEFAULTVALUE|NOT_MAPPED|NO_INHERIT',          # src=yes doc=no
    STANDARDFONT => 'NOT_MAPPED',                             # src=yes doc=no
    TIP => 'NO_DEFAULTVALUE|NO_INHERIT',                      # src=yes doc=no
    TIPBGCOLOR => 'NOT_MAPPED',                               # src=yes doc=no
    TIPDELAY => 'NOT_MAPPED',                                 # src=yes doc=no
    TIPFGCOLOR => 'NOT_MAPPED',                               # src=yes doc=no
    TIPVISIBLE => 'NO_INHERIT',                               # src=yes doc=no
    UNMAP_CB => 'NO_INHERIT',                                 # src=yes doc=no
    VISIBLE => 'DEFAULT',                                     # src=yes doc=no
    WID => 'READONLY|NO_INHERIT|NO_STRING',                   # src=yes doc=no
    X => 'READONLY|NO_INHERIT',                               # src=yes doc=no
    XFONTID => 'NOT_MAPPED|NO_INHERIT|NO_STRING',             # src=yes doc=no
    XFONTSTRUCT => 'NOT_MAPPED|NO_INHERIT|NO_STRING',         # src=yes doc=no
    XMFONTLIST => 'NOT_MAPPED|NO_INHERIT|NO_STRING',          # src=yes doc=no
    Y => 'READONLY|NO_INHERIT',                               # src=yes doc=no
    ZORDER => 'WRITEONLY|NO_INHERIT',                         # src=yes doc=no
  },
  '_box' => {
    CGAP => 'NOT_MAPPED',                                     # src=yes doc=no
    CLIENTSIZE => 'READONLY|NOT_MAPPED|NO_INHERIT',           # src=yes doc=no
    CMARGIN => 'NOT_MAPPED',                                  # src=yes doc=no
    EXPANDCHILDREN => 'NOT_MAPPED|NO_INHERIT',                # src=yes doc=no
    GAP => 'NOT_MAPPED',                                      # src=yes doc=no
    HOMOGENEOUS => 'NOT_MAPPED|NO_INHERIT',                   # src=yes doc=no
    MARGIN => 'NOT_MAPPED',                                   # src=yes doc=no
    NCGAP => 'NOT_MAPPED|NO_INHERIT',                         # src=yes doc=no
    NCMARGIN => 'NOT_MAPPED|NO_INHERIT',                      # src=yes doc=no
    NGAP => 'NOT_MAPPED|NO_INHERIT',                          # src=yes doc=no
    NMARGIN => 'NOT_MAPPED|NO_INHERIT',                       # src=yes doc=no
    NORMALIZESIZE => 'NOT_MAPPED|NO_INHERIT',                 # src=yes doc=no
  },
  '_dialog' => {
    BACKGROUND => 'DEFAULT',                                  # src=yes doc=yes
    BGCOLOR => 'DEFAULT',                                     # src=yes doc=yes
    BORDER => 'NO_INHERIT',                                   # src=yes doc=yes
    BRINGFRONT => 'NO_INHERIT',                               # src=yes doc=yes
    CLIENTSIZE => 'NO_DEFAULTVALUE|READONLY|NO_INHERIT',      # src=yes doc=yes
    COMPOSITED => 'NOT_MAPPED',                               # src=yes doc=yes
    CONTROL => 'NO_INHERIT',                                  # src=yes doc=yes
    CURSOR => 'NO_INHERIT',                                   # src=yes doc=yes
    DEFAULTENTER => 'NO_INHERIT',                             # src=yes doc=yes
    DEFAULTESC => 'NO_INHERIT',                               # src=yes doc=yes
    DIALOGFRAME => 'NO_INHERIT',                              # src=yes doc=yes
    DIALOGHINT => 'NO_INHERIT',                               # src=yes doc=yes
    DRAGDROP => 'NO_INHERIT',                                 # src=yes doc=yes
    FULLSCREEN => 'WRITEONLY|NO_INHERIT',                     # src=yes doc=yes
    HELPBUTTON => 'NO_INHERIT',                               # src=yes doc=yes
    HIDETASKBAR => 'NO_INHERIT',                              # src=yes doc=yes
    HWND => 'NO_STRING|NO_INHERIT',                           # src=yes doc=yes
    ICON => 'NO_INHERIT',                                     # src=yes doc=yes
    LAYERALPHA => 'NO_INHERIT',                               # src=yes doc=no
    MAXBOX => 'NO_INHERIT',                                   # src=yes doc=yes
    MDIACTIVATE => 'WRITEONLY|NO_INHERIT',                    # src=yes doc=yes
    MDIACTIVE => 'READONLY|NO_INHERIT',                       # src=yes doc=yes
    MDIARRANGE => 'WRITEONLY|NO_INHERIT',                     # src=yes doc=yes
    MDICHILD => 'NO_INHERIT',                                 # src=yes doc=yes
    MDICLIENT => 'NO_INHERIT',                                # src=yes doc=yes
    MDICLOSEALL => 'WRITEONLY|NO_INHERIT',                    # src=yes doc=yes
    MDIFRAME => 'NO_INHERIT',                                 # src=yes doc=yes
    MDIMENU => 'NO_INHERIT',                                  # src=yes doc=yes
    MDINEXT => 'READONLY|NO_INHERIT',                         # src=yes doc=yes
    MENU => 'NOT_MAPPED|NO_INHERIT',                          # src=yes doc=yes
    MENUBOX => 'NO_INHERIT',                                  # src=yes doc=yes
    MINBOX => 'NO_INHERIT',                                   # src=yes doc=yes
    MODAL => 'READONLY|NO_INHERIT',                           # src=yes doc=yes
    NATIVEPARENT => 'NO_STRING',                              # src=yes doc=yes
    OPACITY => 'NO_INHERIT',                                  # src=yes doc=yes
    PARENTDIALOG => 'NO_INHERIT',                             # src=yes doc=yes
    PLACEMENT => 'NO_INHERIT',                                # src=yes doc=yes
    RESIZE => 'NO_INHERIT',                                   # src=yes doc=yes
    SAVEUNDER => 'NO_INHERIT',                                # src=yes doc=yes
    SHRINK => 'NO_INHERIT',                                   # src=yes doc=yes
    STARTFOCUS => 'NO_INHERIT',                               # src=yes doc=yes
    TITLE => 'NO_DEFAULTVALUE|NO_INHERIT',                    # src=yes doc=yes
    TOOLBOX => 'NO_INHERIT',                                  # src=yes doc=yes
    TOPMOST => 'WRITEONLY|NO_INHERIT',                        # src=yes doc=yes
    TRAY => 'NO_INHERIT',                                     # src=yes doc=yes
    TRAYIMAGE => 'NO_INHERIT',                                # src=yes doc=yes
    TRAYTIP => 'NO_INHERIT',                                  # src=yes doc=yes
    XWINDOW => 'NO_INHERIT|NO_STRING',                        # src=yes doc=yes
  },
};

sub _get_attr_list {
  my $pkg = shift;
  my @rv = ();
  push(@rv, keys(%{$attrib_table->{_base}}));
  push(@rv, keys(%{$attrib_table->{_dialog}})) if $pkg =~ /^IUP::(Dialog|ColorDlg|FileDlg|FontDlg|MessageDlg)$/;
  push(@rv, keys(%{$attrib_table->{_box}}))    if $pkg =~ /^IUP::[CHVZ]box$/;
  push(@rv, keys(%{$attrib_table->{$pkg}}));
  return @rv;
}

sub _is_attr_valid {
  my ($pkg, $name) = @_;
  #my $h = $attrib_table->{$pkg};
  #return 0 unless defined($h);
  #return defined($h->{$name}) ? 1 : 0;
  carp "Warning: DO NOT USE _is_attr_valid!";
  return 1;
}

sub _get_attr_eval_code {
  my ($element, $p) = @_;
  my $rv = '';
  my $h = $attrib_table->{$element} or return $rv;
  
  for (keys %$h) {
    next if defined *{"$p\::$_"};
    $rv .= "*$p\::$_ = sub { return \$_[1] ? \$_[0]->SetAttribute('$_', \$_[1]) : \$_[0]->GetAttribute('$_') };\n";
  }

  return $rv;
}


1;

__END__

=head1 NAME

IUP::Internal::Attribute - INTERNAL FUNCTIONS, do not use them from outside!

=cut 