=head1 IupHbox

Creates a void container for composing elements horizontally. It is a
box that arranges the elements it contains from left to right.

It does not have a native representation.

=head2 Creation

 Ihandle* IupHbox(Ihandle *child, ...); [in C]
 Ihandle* IupHboxv(Ihandle **children); [in C]
 iup.hbox{child, ...: ihandle} -> (elem: ihandle) [in Lua]
 hbox(child, ...) [in LED]

B<child>,... : List of identifiers that will be placed in the box. NULL
must be used to define the end of the list in C. It can be empty.

Returns: the identifier of the created element, or NULL if an error
occurs.

=head2 Attributes

B<ALIGNMENT> (non inheritable): Aligns the elements vertically.
Possible values: "ATOP", "ACENTER", "ABOTTOM". Default: "ATOP".

L<EXPAND|../attrib/iup_expand.html> (non inheritable*): The default
value is "YES". See the documentation of the attribute for EXPAND
inheritance.

B<EXPANDCHILDREN> (non inheritable): forces all children to expand
vertically. Default: "NO". This has the same effect as setting
EXPAND=VERTICAL on each child, but their horizontal expansion will be
preserved. (since 3.0)

B<EXPANDWEIGHT> (non inheritable) B<(at children only)>: If a child
defines the expand weight, then it is used to multiply the free space
used for expansion. (since 3.1)

L<FLOATING|../attrib/iup_floating.html> (non inheritable) B<(at
children only)>: If a child has FLOATING=YES then its size and position
will be ignored by the layout processing. Default: "NO". (since 3.0)

B<GAP, CGAP>: Defines an horizontal space in pixels between the
children, B<CGAP> is in the same units of the B<SIZE> attribute for the
width. Default: "0". (CGAP since 3.0)

B<NGAP, NCGAP> (non inheritable): Same as B< GAP> but are non
inheritable. (since 3.0)

B<HOMOGENEOUS> (non inheritable): forces all children to get equal
horizontal space. The natural size width will be based on the largest
child. Default: "NO". Notice that this does not changes the children
size, only the available space for each one of them to expand. (since
3.0)

B<MARGIN, CMARGIN>: Defines a margin in pixels, B<CMARGIN >is in the
same units of the B< SIZE> attribute. Its value has the format
"I<width>xI<height>", where I< width> and I<height> are integer values
corresponding to the horizontal and vertical margins, respectively.
Default: "0x0" (no margin). (CMARGIN since 3.0)

B<NMARGIN, NCMARGIN> (non inheritable): Same as B<MARGIN> but are non
inheritable. (since 3.0)

B<NORMALIZESIZE> (non inheritable): normalizes all children natural
size to be the biggest natural size among them. All natural width will
be set to the biggest width, and all natural height will be set to the
biggest height according to is value. Can be NO, HORIZONTAL, VERTICAL
or BOTH. Default: "NO". (since 3.0)

L<SIZE|../attrib/iup_size.html> /
L<RASTERSIZE|../attrib/iup_rastersize.html> (non inheritable): Defines
the width of the box. When consulted behaves as the standard
SIZE/RASTERSIZE attributes. The standard format "wxh" can also be used,
but height will be ignored (since 3.3).

B<WID> (read-only): returns -1 if mapped.

=over

----

=back

L<FONT|../attrib/iup_font.html>,
L<CLIENTSIZE|../attrib/iup_clientsize.html>,
L<CLIENTOFFSET|../attrib/iup_clientoffset.html>,
L<POSITION|../attrib/iup_position.html>,
L<MINSIZE|../attrib/iup_minsize.html>,
L<MAXSIZE|../attrib/iup_maxsize.html>: also accepted.

=head2 Notes

The box can be created with no elements and be dynamic filled using
L<IupAppend|../func/iupappend.html> or
L<IupInsert|../func/iupinsert.html>.

The box will NOT expand its children, it will allow its children to
expand according to the space left in the box parent. So for the
expansion to occur, the children must be expandable with EXPAND!=NO,
and there must be room in the box parent.

=head2 Examples

L<Browse for Example Files|../../examples/>

[IMAGE]

[IMAGE]

HOMOGENEOUS=YES

[IMAGE]

EXPANDCHILDREN=YES

[IMAGE]

=head2 X<SeeAlso>See Also

L<IupZbox|iupzbox.html>, L<IupVBox|iupvbox.html>

=cut