=head1 IupText

Creates an editable text field.

=head2 Creation

 Ihandle* IupText(const char *action); [in C]iup.text{} -> (elem: ihandle) [in Lua]text(action) [in LED]

B<action>: name of the action generated when the user types something.
It can be NULL.

Returns: the identifier of the created element, or NULL if an error
occurs.

=head2 Attributes

B<ALIGNMENT> [Windows and GTK Only] (non inheritable): text alignment.
Possible values: "ALEFT", "ARIGHT", "ACENTER". Default: "ALEFT". In
Motif, text is always left aligned.

B<APPEND> (write-only): Inserts a text at the end of the current text.
In the Multiline, if APPENDNEWLINE=YES, a "\n" character will be
automatically inserted before the appended text if the current text is
not empty(APPENDNEWLINE default is YES). Ignored if set before map.

L<BGCOLOR|../attrib/iup_bgcolor.html>: Background color of the text.
Default: the global attribute TXTBGCOLOR.

B<BORDER >(creation only): Shows a border around the text. Default:
"YES".

B<CANFOCUS> (creation only) (non inheritable): enables the focus
traversal of the control. In Windows the control will still get the
focus when clicked. Default: YES. (since 3.0)

B<CARET> (non inheritable): B<Character >position of the insertion
point. Its format depends in MULTILINE=YES. The first position, B<lin>
or B<col>, is "1".

B<For multiple lines>: a string with the "B<lin>,B<col>" format, where
B<lin> and B<col> are integer numbers corresponding to the caret's
position.

B<For single line>: a string in the "B<col>" format, where B<col> is an
integer number corresponding to the caret's position.

When B<lin> is greater than the number of lines, the caret is placed at
the last line. When B<col> is greater than the number of characters in
the given line, the caret is placed after the last character of the
line.

If the caret is not visible the text is scrolled to make it visible.

In Windows, if the element does not have the focus the returned value
is the position of the first character of the current selection. The
caret is only displayed if the element has the keyboard focus, but its
position can be changed even if not visible. When changed it will also
change the selection but the text will be scrolled only when it
receives the focus.

See the Notes below if using UTF-8 strings in GTK.

B<CARETPOS> (non inheritable): Also the B<character >position of the
insertion point, but using a zero based character unique index "pos".
Useful for indexing the VALUE string. See the Notes below if using
UTF-8 strings in GTK. (since 3.0)

B<CLIPBOARD> (write-only): clear, cut, copy or paste the selection to
or from the clipboard. Values: "CLEAR", "CUT", "COPY" or "PASTE". In
Windows UNDO is also available, and REDO is available when
FORMATTING=YES. (since 3.0)

B<COUNT> (read-only): returns the number of B<characters> in the text.
(since 3.5)

B<CUEBANNER> [Windows Only] (non inheritable): a text that is displayed
when there is no text at the control. It works as a textual cue, or tip
to prompt the user for input. Valid only for MULTILINE=NO, and it is
not available for Windows 2000. (since 3.0)

B<DROPFILESTARGET> [Windows and GTK Only] (non inheritable): Enable or
disable the drop of files. Default: NO, but if DROPFILES_CB is defined
when the element is mapped then it will be automatically enabled.
(since 3.0)

L<FGCOLOR|../attrib/iup_fgcolor.html>: Text color. Default: the global
attribute TXTFGCOLOR.

B<FILTER> [Windows Only] (non inheritable): allows a custom filter to
process the characters: Can be LOWERCASE, UPPERCASE or NUMBER (only
numbers allowed). (since 3.0)

L<FORMATTING|../attrib/iup_formatting.html> [Windows and GTK Only] (non
inheritable): When enabled allow the use of text formatting attributes.
In GTK is always enabled, but only when MULTILINE=YES. Default: NO.
(since 3.0)

B<INSERT> (write-only): Inserts a text in the caret's position, also
replaces the current selection if any. Ignored if set before map.

B<LINECOUNT> (read-only): returns the number of lines in the text. When
MULTILINE=NO returns always "1". (since 3.5)

B<LINEVALUE> (read-only): returns the text of the line where the caret
is. It does not include the "\n" character. When MULTILINE=NO returns
the same as VALUE. (since 3.5)

L<MASK|../attrib/iup_mask.html> (non inheritable): Defines a mask that
will filter interactive text input.

B<MULTILINE> (creation only) (non inheritable): allows the edition of
multiple lines. In single line mode some characters are invalid, like
"\t", "\r" and "\n". Default: NO. When set to Yes will also reset the
SCROLLBAR attribute to Yes.

B<NC>: Maximum number of B<characters> allowed for keyboard input,
larger text can still be set using attributes. The maximum value is the
limit of the VALUE attribute. The "0" value is the same as maximum.
Default: maximum.

B<OVERWRITE> [Windows and GTK Only] (non inheritable): turns the
overwrite mode ON or OFF. Works only when FORMATTING=YES. (since 3.0)

B<PADDING>: internal margin. Works just like the MARGIN attribute of
the B<IupHbox> and B<IupVbox> containers, but uses a different name to
avoid inheritance problems. Default value: "0x0". In Windows, only the
horizontal value is used. (since 3.0) (GTK 2.10 for single line)

B<PASSWORD >(creation only) [Windows and GTK Only] (non inheritable):
Hide the typed character using an "*". Default: "NO".

B<READONLY>: Allows the user only to read the contents, without
changing it. Restricts keyboard input only, text value can still be
changed using attributes. Navigation keys are still available. Possible
values: "YES", "NO". Default: NO.

B<SCROLLBAR> (creation only): Valid only when MULTILINE=YES. Associates
an automatic horizontal and/or vertical scrollbar to the multiline. Can
be: "VERTICAL", "HORIZONTAL", "YES" (both) or "NO" (none). Default:
"YES". For all systems, when SCROLLBAR!=NO the natural size will always
include its size even if the native system hides the scrollbar. If
B<AUTOHIDE>=YES scrollbars are visible only if they are necessary, by
default AUTOHIDE=NO. In Windows when FORMATTING=NO, AUTOHIDE is not
supported. In Motif AUTOHIDE is not supported.

B<SCROLLTO> (non inheritable, write only): Scroll the text to make the
given B<character >position visible. It uses the same format and
reference of the CARET attribute ("lin:col" or "col" starting at 1). In
Windows, when FORMATTING=Yes "col" is ignored. (since 3.0)

B<SCROLLTOPOS> (non inheritable, write only): Scroll the text to make
the given B<character >position visible. It uses the same format and
reference of the CARETPOS attribute ("pos" starting at 0). (since 3.0)

B<SELECTEDTEXT> (non inheritable): Selection text. Returns NULL if
there is no selection. When changed replaces the current selection.
Similar to INSERT, but does nothing if there is no selection.

B<X<SELECTION>SELECTION> (non inheritable): Selection interval in
B<characters>. Returns NULL if there is no selection. Its format
depends in MULTILINE=YES. The first position, B<lin> or B<col>, is "1".

B<For multiple lines>: a string in the
"B<lin1>,B<col1>:B<lin2>,B<col2>" format, where B<lin1>, B<col1>,
B<lin2> and B<col2> are integer numbers corresponding to the
selection's interval. B<col2> correspond to the character after the
last selected character.

B<For single line>: a string in the "B<col1>:B<col2>" format, where
B<col1> and B<col2> are integer numbers corresponding to the
selection's interval. B<col2> correspond to the character after the
last selected character.

In Windows, when changing the selection the caret position is also
changed.

The values ALL and NONE are also accepted independently of MULTILINE
(since 3.0).

See the Notes below if using UTF-8 strings in GTK.

B<SELECTIONPOS> (non inheritable): Same as SELECTION but using a zero
based B<character> index "B<pos1>:B<pos2>". Useful for indexing the
VALUE string. The values ALL and NONE are also accepted. See the Notes
below if using UTF-8 strings in GTK. (since 3.0)

L<SIZE|../attrib/iup_size.html> (non inheritable): Since the contents
can be changed by the user, the B<Natural> B<Size> is not affected by
the text contents (since 3.0). In IUP 2.x the B<Natural> B<Size> was
defined by the number of lines in the text and the with of the largest
line. For IUP 3, use VISIBLECOLUMNS and VISIBLELINES to control the
B<Natural Size>.

B<SPIN> (non inheritable, creation only): enables a spin control
attached to the element. Default: NO. The spin increments and
decrements an integer number. The editing in the element is still
available. (since 3.0)

B<SPINVALUE >(non inheritable): the current value of the spin. The
value is limited to the minimum and maximum values.

B<SPINMAX >(non inheritable): the maximum value. Default: 100.

B<SPINMIN >(non inheritable): the minimum value. Default: 0.

B<SPININC >(non inheritable): the increment value. Default: 1.

B<SPINALIGN> (creation only): the position of the spin. Can be LEFT or
RIGHT. Default: RIGHT. In GTK is always RIGHT.

B<SPINWRAP> (creation only): if the position reach a limit it continues
from the opposite limit. Default: NO.

B<SPINAUTO> (creation only): enables the automatic update of the text
contents. Default: YES. Use SPINAUTO=NO and the VALUE attribute during
SPIN_CB to control the text contents when the spin is incremented.

In Windows, the increment is multiplied by 5 after 2 seconds and
multiplied by 20 after 5 seconds of a spin button pressed. In GTK, the
increment change is progressively accelerated when a spin button is
pressed.

B<TABSIZE> [Windows and GTK Only]: Valid only when MULTILINE=YES.
Controls the number of characters for a tab stop. Default: 8.

B<VALUE >(non inheritable): Text entered by the user. The '\n'
character indicates a new line, valid only when MULTILINE=YES. After
the element is mapped and if there is no text will return the empty
string "".

B<VALUEMASKED >(non inheritable) (write-only): sets VALUE but first
checks if it is validated by MASK. If not does nothing. (since 3.4)

B<VISIBLECOLUMNS>: Defines the number of visible columns for the
B<Natural> B<Size>, this means that will act also as minimum number of
visible columns. It uses a wider character size then the one used for
the SIZE attribute so strings will fit better without the need of extra
columns. As for SIZE you can set to NULL after map to use it as an
initial value. Default: 5 (since 3.0)

B<VISIBLELINES>: When MULTILINE=YES defines the number of visible lines
for the B<Natural> B<Size>, this means that will act also as minimum
number of visible lines. As for SIZE you can set to NULL after map to
use it as an initial value. Default: 1 (since 3.0)

B<WORDWRAP> (creation only): Valid only when MULTILINE=YES. If enabled
will force a word wrap of lines that are greater than the with of the
control, and the horizontal scrollbar will be removed. Default: NO.

=over

----

=back

L<ACTIVE|../attrib/iup_active.html>, L<FONT|../attrib/iup_font.html>,
L<EXPAND|../attrib/iup_expand.html>,
L<SCREENPOSITION|../attrib/iup_screenposition.html>,
L<POSITION|../attrib/iup_position.html>,
L<MINSIZE|../attrib/iup_minsize.html>,
L<MAXSIZE|../attrib/iup_maxsize.html>, L<WID|../attrib/iup_wid.html>,
L<TIP|../attrib/iup_tip.html>,
L<RASTERSIZE|../attrib/iup_rastersize.html>,
L<ZORDER|../attrib/iup_zorder.html>,
L<VISIBLE|../attrib/iup_visible.html>: also accepted.

L<Drag E<amp> Drop|../attrib/iup_dragdrop.html> attributes are
supported. See Notes bellow.

=head2 Callbacks

L<ACTION|../call/iup_action.html>: Action generated when the text is
edited, but before its value is actually changed. Can be generated when
using the keyboard, undo system or from the clipboard.

 int function(Ihandle *ih, int c, char *new_value); [in C]elem:action(c: number, new_value: string) -> (ret: number) [in Lua]

B<ih>: identifier of the element that activated the event.

B<c>: valid alpha numeric character or 0.

B<new_value>: Represents the new text value.

Returns: IUP_CLOSE will be processed, but the change will be ignored.
If IUP_IGNORE, the system will ignore the new value. If B<c> is valid
and returns a valid alpha numeric character, this new character will be
used instead. The VALUE attribute can be changed only if IUP_IGNORE is
returned.

L<BUTTON_CB|../call/iup_button_cb.html>: Action generated when any
mouse button is pressed or released. Use
L<IupConvertXYToPos|../func/iupconvertxytopos.html> to convert (x,y)
coordinates in character positioning. (since 3.0)

B<CARET_CB>: Action generated when the caret/cursor position is
changed.

 int function(Ihandle *ih, int lin, int col, int pos); [in C]elem:caret_cb(lin, col, pos: number) -> (ret: number) [in Lua]

B<ih>: identifier of the element that activated the event.

B<lin, col>: line and column number (start at 1).

B<pos>: 0 based character position.

For single line controls B<lin> is always 1, and B<pos> is always
"B<col>-1".

L<DROPFILES_CB|../call/iup_dropfiles_cb.html> [Windows and GTK Only]:
Action generated when one or more files are dropped in the element.
(since 3.0)

L<MOTION_CB|../call/iup_motion_cb.html>: Action generated when the
mouse is moved. Use L<IupConvertXYToPos|../func/iupconvertxytopos.html>
to convert (x,y) coordinates in character positioning. (since 3.0)

B<SPIN_CB>: Action generated when a spin button is pressed. Valid only
when SPIN=YES. When this callback is called the ACTION callback is not
called. The VALUE attribute can be changed during this callback only if
SPINAUTO=NO. (since 3.0)

 int function(Ihandle *ih, int pos); [in C]elem:spin_cb(pos: number) -> (ret: number) [in Lua]

B<ih>: identifier of the element that activated the event.

B<pos>: the value of the spin (after it was incremented).

Returns: IUP_IGNORE is processed in Windows and Motif.

B<VALUECHANGED_CB>: Called after the value was interactively changed by
the user. (since 3.0)

 int function(Ihandle *ih); [in C]elem:valuechanged_cb() -> (ret: number) [in Lua]

B<ih>: identifier of the element that activated the event.

----

L<MAP_CB|../call/iup_map_cb.html>,
L<UNMAP_CB|../call/iup_unmap_cb.html>,
L<GETFOCUS_CB|../call/iup_getfocus_cb.html>,
L<KILLFOCUS_CB|../call/iup_killfocus_cb.html>,
L<ENTERWINDOW_CB|../call/iup_enterwindow_cb.html>,
L<LEAVEWINDOW_CB|../call/iup_leavewindow_cb.html>,
L<K_ANY|../call/iup_k_any.html>, L<HELP_CB|../call/iup_help_cb.html>:
All common callbacks are supported.

L<Drag E<amp> Drop|../attrib/iup_dragdrop.html> callbacks are
supported. See Notes bellow.

=head2 X<AUX>Auxiliary Functions

 void IupTextConvertLinColToPos(Ihandle* ih, int lin, int col, int *pos); [in C]iup.TextConvertLinColToPos(ih: ihandle, lin, col: number) -> pos: number [in Lua]

Converts a (lin, col) character positioning into an absolute position.
For single line controls B<pos> is always "B<col>-1". (since 3.0)

 void IupTextConvertPosToLinCol(Ihandle* ih, int pos, int *lin, int *col); [in C]iup.TextConvertPosToLinCol(ih: ihandle, pos: number) -> lin, col: number [in Lua]

Converts an absolute position into a (lin, col) character positioning.
For single line controls B<lin> is always 1, and B<col> is always
"B<pos>+1". (since 3.0)

=head2 Notes

When MULTILINE=YES the Enter key will add a new line, and the Tab key
will insert a Tab. So the "DEFAULTENTER" button will not be processed
when the element has the keyboard focus, also to change focus to the
next element press E<lt>CtrlE<gt>+E<lt>TabE<gt>.

In Windows, if you press a Ctrl+key combination that is not supported
by the control, then a beep is sound.

When using UTF-8 strings in GTK be aware that all attributes are
indexed by characters, NOT by byte index, because some characters in
UTF-8 can use more than one byte. This also applies to Windows if
FORMATTING=YES depending on the Windows codepage (for example East
Asian codepage where some characters take two bytes).

Internal Drag&Drop support is enabled by default. But in Windows the
internal Drag&Drop is enabled only if FORMATTING=YES. In GTK the
internal Drag&Drop can NOT be disabled, so it will conflict with the
L<Drag E<amp> Drop|../attrib/iup_dragdrop.html> attributes and
callbacks.

=head2 Navigation, Selection and Clipboard Keys

Here is a list of the common keys for all drivers. Other keys are
available depending on the driver.

Keys

Action

I<Navigation>

Arrows

move by individual characters/lines

Ctrl+Arrows

move by words/paragraphs

Home/End

move to begin/end line

Ctrl+Home/End

move to begin/end text

PgUp/PgDn

move vertically by pages

Ctrl+PgUp/PgDn

move horizontally by pages

I<Selection>

Shift+Arrows

select charaters

Ctrl+A

select all

I<Deleting>

Del

delete the character at right

Backspace

delete the character at left

I<Clipboard>

Ctrl+C

copy

Ctrl+X

cut

Ctrl+V

paste

=head2 Examples

L<Browse for Example Files|../../examples/>

Motif

Windows

Classic

Windows

w/ Styles

GTK

[IMAGE]

[IMAGE]

[IMAGE]

[IMAGE]

When FORMATTING=YES in Windows or GTK (formatting attributes are set to
a formatag object that it is a B<IupUser>):

 "ALIGNMENT" = "CENTER""SPACEAFTER" = "10""FONTSIZE" = "24""SELECTION" = "3,1:3,50""ADDFORMATTAG""BGCOLOR" = "255 128 64""UNDERLINE" = "SINGLE""WEIGHT" = "BOLD""SELECTION" = "3,7:3,11""ADDFORMATTAG"    "ITALIC" = "YES""STRIKEOUT" = "YES""SELECTION" = "2,1:2,12""ADDFORMATTAG"

[IMAGE]

When SPIN=YES:

Motif

Windows

Classic

Windows

w/ Styles

GTK

[IMAGE]

[IMAGE]

[IMAGE]

[IMAGE]

=head2 X<SeeAlso>See Also

L<IupList|iuplist.html>, L<IupMultiLine|iupmultiline.html>

=cut