=head1 CLIENTSIZE (read-only*) (non inheritable) (since 3.0)

Returns the client area size of a container. It is the space available
for positioning and sizing children, see the L<Layout
Guide|../layout_guide.html>. It is the container B<Current> size
excluding the decorations (if any).

=head2 Value

"I<width>xI<height>", where I<width> and I<height> are integer values
corresponding to the horizontal and vertical size, respectively, in
pixels.

=head2 Affects

All elements that are containers, except menus.

=head2 Notes

For B<IupHbox>, B<IupVbox> and B<IupGridBox> it consider the MARGIN
attribute as a decoration.

For B<IupDialog>, B<IupBackgroundBox>, B< IupScrollBox> and
B<IupGLCanvasBox> is only available after the control is mapped.

For B<IupDialog> is NOT read-only, and it will re-define RASTERSIZE by
adding the decorations to the actual Client size. (Since 3.3)

For B<IupSplit> returns the total area available for the two children.

=head2 See Also

L<SIZE|iup_size.html>, L<RASTERSIZE|iup_rastersize.html>,
L<CLIENTOFFSET|iup_clientoffset.html>

=cut