=head1 FGCOLOR

ElementE<rsquo>s foreground color. Usually it is the color of the
associated text.

=head2 Value

The RGB components. Values should be between 0 and 255, separated by a
blank space.

Default: "0 0 0".

Hexadecimal notation in the format "#RRGGBB" is also accepted in all
color attributes. For example, "255 0 128" can also be written as
"#FF0080".

=head2 Affects

All.

=head2 See Also

L<BGCOLOR|iup_bgcolor.html>

=cut