=head1 FLOATING (non inheritable) (since 3.0)

If an element has FLOATING=YES then its size and position will be
ignored by the layout processing in B<IupVbox>, B<IupHbox> and
B<IupZbox>. But the element size and position will still be updated in
the native system allowing the usage of B<SIZE>/B<RASTERSIZE> and
B<POSITION> to manually position and size the element.

This is useful when you do not want that an invisible element to be
computed in the box size.

If the value IGNORE is used then it will behave as YES, but also it
will not update the the size and position in the native system. (since
3.3)

=head2 Value

"YES", "IGNORE" (since 3.3) or "NO".

Default: "NO".

=head2 Affects

All elements, except menus.

=head2 X<SeeAlso>See Also

L<IupZbox|../elem/iupzbox.html>, L<IupVBox|../elem/iupvbox.html>,
L<IupHBox|../elem/iuphbox.html>

=cut