=head1 YMAX

Maximum value of the vertical scrollbar, in any unit.

=head2 Value

Any floating-point value.

Default: "1.0"

=head2 Notes

A change in this value will only be effective after the attribute
L<DY|iup_dy.html> is changed.

=head2 Affects

L<IupCanvas|../elem/iupcanvas.html>

=head2 See Also

L<SCROLLBAR|iup_scrollbar.html>

=cut