=head1 CONTROL

B<Windows only.> Whether the dialog is embedded inside the parent
window or has a window of its own.

=head2 Value

YES or NO. If the value is YES, the dialog will appear embedded inside
its parent window (you must set a parent, either with PARENTDIALOG or
NATIVEPARENT, or this setting will be ignored). If the value is NO, the
dialog will have its own window.

=head2 Notes

This is useful for implementing ActiveX controls, with the help of the
L<LuaCOM|http://www.tecgraf.puc-rio.br/~rcerq/luacom/> library. ActiveX
controls run embedded inside another window. LuaCOM will send a window
creation event the the control, passing a handle to the parent window
and the size of the control. You can use this to set the dialog's
NATIVEPARENT and RASTERSIZE attributes. See the
L<LuaCOM|http://www.tecgraf.puc-rio.br/~rcerq/luacom/> documentation
for more information.

=head2 Affects

IupDialog

=head2 See Also

B<L<NATIVEPARENT|../dlg/iupdialog.html#Attributes>>, B<
L<PARENTDIALOG|../dlg/iupdialog.html#Attributes>>, B<
L<RASTERSIZE|iup_rastersize.html>>

=cut