=head1 PARENTDIALOG

The parent dialog of a dialog.

=head2 Value

Name of a dialog to be used as parent.

Default: NULL.

=head2 Notes

This dialog will be always in front of the parent dialog. If the parent
is minimized, this dialog is automatically minimized. The parent dialog
must be mapped before mapping the child dialog.

If PARENTDIALOG is not defined then the NATIVEPARENT attribute is
consulted. This one must be a native handle of an existing dialog.

Use L<IupSetHandle|../func/iupsethandle.html> or
L<IupSetAttributeHandle|../func/iupsetattributehandle.html> to
associate a dialog to a name.

B<IMPORTANT>: When the parent is destroyed the child dialog is also
destroyed, BUT the CLOSE_CB callback of the child dialog is NOT called.
The application must take care of destroying the child dialogs before
destroying the parent. This is usually done when CLOSE_CB of the parent
dialog is called.

=head2 Affects

L<IupDialog|../dlg/iupdialog.html>

=cut