=head1 POSITION (non inheritable)

The position of the element relative to the origin of the B<Client>
area of the native parent. If you add the CLIENTOFFSET attribute of the
native parent, you can obtain the coordinates relative to the B<Window>
area of the native parent. See the L<Layout
Guide|../layout_guide.html>.

It will be changed during the layout computation, except when
FLOATING=YES or when used inside a concrete layout container.

=head2 Value

"x,y", where I<x> and I<y> are integer values corresponding to the
horizontal and vertical position, respectively, in pixels.

=head2 Affects

All, except menus.

=head2 See Also

L<SIZE|iup_size.html>, L<RASTERSIZE|iup_rastersize.html>,
L<FLOATING|iup_floating.html>, L<CLIENTOFFSET|iup_clientoffset.html>

=cut