=for comment based on iup-3.32 - http://www.tecgraf.puc-rio.br/iup/en/ctrl/iupglbackgroundbox.html

=head1 NAME

IUP::GL::BackgroundBox - [GUI element] GL-based background box

=head1 DESCRIPTION

A void background container that is drawn by IUP on an OpenGL canvas. It
has no decorations, but with OpenGL enabled. It inherits from
L<IUP::CanvasGL|IUP::CanvasGL>. This is identical to the
L<IUP::BackgroundBox|IUP::BackgroundBox> element, but with OpenGL
enabled. (since iup-3.18)

=head1 USAGE

=head2 CREATION - new() method

 my $box = IUP::GL::BackgroundBox->new( child=>$something );

B<child>: An interface element which will receive the box. It can be
C<undef>.

B<Returns:> the identifier of the created element, or C<undef> if an error occurs.

=head2 ATTRIBUTES

For more info about concept of attributes (setting/getting values etc.)
see L<IUP::Manual::03_Attributes|IUP::Manual::03_Attributes>. Attributes specific to this element:

=over

=item L<BGCOLOR|IUP::Manual::03_Attributes/BGCOLOR>

By default will use the background color of the native parent, but can
be set to a custom value. (since iup-3.11)

=item B<BORDER>

I<(creation only)>

The default value is "NO".

=item B<CANVASBOX>

I<(non inheritable)>

Enables the behavior of a canvas box instead of a regular container.
This will affect the EXPAND attribute, the Natural size computation, and
children layout distribution. Can be "YES" or "NO". Default: "NO".
(since iup-3.19)

=item B<CHILDOFFSET>

I<(non inheritable)>

Allows to specify a position offset for the child. Available for native
containers only. It will not affect the natural size, and allows to
position controls outside the client area. Format "I<dx>xI<dy>", where
I<dx> and I<dy> are integer values corresponding to the horizontal and
vertical offsets, respectively, in pixels. Default: "0x0".
(since iup-3.14)

=item B<DECORATION>

I<(non inheritable)>

Enables a decoration area around the child. Can be "YES" or "NO".
Default: "NO". (since iup-3.20)

=item B<DECORSIZE>

I<(non inheritable)>

Total size of the decoration in the format "WidthxHeight". Used only
when DECORATION=Yes. (since iup-3.20)

=item B<DECOROFFSET>

I<(non inheritable)>

Decoration offset from left border and top border in the format "XxY".
Used only when DECORATION=Yes. (since iup-3.20)

=item L<EXPAND|IUP::Manual::03_Attributes/EXPAND>

I<(non inheritable)>

Behaves as a container. See the CANVASBOX attribute.

=item B<CANFOCUS>

I<(non inheritable)>

The default is changed to "NO". But it can receive the focus.
(since iup-3.19)

=back

The following L<common attributes|IUP::Manual::03_Attributes/Common Attributes> are also accepted:

=over

=item * L<ACTIVE|IUP::Manual::03_Attributes/ACTIVE>,
L<FONT|IUP::Manual::03_Attributes/FONT>,
L<EXPAND|IUP::Manual::03_Attributes/EXPAND>,
L<SCREENPOSITION|IUP::Manual::03_Attributes/SCREENPOSITION>,
L<POSITION|IUP::Manual::03_Attributes/POSITION>,
L<MINSIZE|IUP::Manual::03_Attributes/MINSIZE>,
L<MAXSIZE|IUP::Manual::03_Attributes/MAXSIZE>,
L<WID|IUP::Manual::03_Attributes/WID>,
L<TIP|IUP::Manual::03_Attributes/TIP>,
L<SIZE|IUP::Manual::03_Attributes/SIZE>,
L<RASTERSIZE|IUP::Manual::03_Attributes/RASTERSIZE>,
L<ZORDER|IUP::Manual::03_Attributes/ZORDER>,
L<VISIBLE|IUP::Manual::03_Attributes/VISIBLE>

=back

=head2 CALLBACKS

For more info about concept of callbacks (setting callback handlers etc.)
see L<IUP::Manual::04_Callbacks|IUP::Manual::04_Callbacks>. Callbacks specific to this element:

=over

=back

The following L<common callbacks|IUP::Manual::04_Callbacks/Common Callbacks> are also accepted:

=over

=item * L<MAP_CB|IUP::Manual::04_Callbacks/MAP_CB>,
L<UNMAP_CB|IUP::Manual::04_Callbacks/UNMAP_CB>,
L<GETFOCUS_CB|IUP::Manual::04_Callbacks/GETFOCUS_CB>,
L<KILLFOCUS_CB|IUP::Manual::04_Callbacks/KILLFOCUS_CB>,
L<ENTERWINDOW_CB|IUP::Manual::04_Callbacks/ENTERWINDOW_CB>,
L<LEAVEWINDOW_CB|IUP::Manual::04_Callbacks/LEAVEWINDOW_CB>,
L<K_ANY|IUP::Manual::04_Callbacks/K_ANY>,
L<HELP_CB|IUP::Manual::04_Callbacks/HELP_CB>

=back

=head1 NOTES

The box can be created with no elements and be dynamically filled using
L<IUP::Append|IUP::Append> or L<IUP::Insert|IUP::Insert>.

The ACTION callback can be defined and the application can draw below
the other children inside the GL::BackgroundBox, but only with the
OpenGL API. To avoid overlapping the drawing areas it is recommended
that children must be inside native containers.

=head1 EXAMPLES


Unfortunately there are no sample scripts using this element.



=head1 SEE ALSO

L<IUP::BackgroundBox|IUP::BackgroundBox>, L<IUP::GL::CanvasBox|IUP::GL::CanvasBox>

The original doc: L<iupglbackgroundbox.html|http://www.tecgraf.puc-rio.br/iup/en/ctrl/iupglbackgroundbox.html>


=cut
