=for comment based on iup-3.32 - http://www.tecgraf.puc-rio.br/iup/en/gl/iupgltext.html

=head1 NAME

IUP::GL::Text - [GUI element] GL-based text lable

=head1 DESCRIPTION

A single-line text entry drawn by IUP on an OpenGL canvas. It displays a text and allows the user to edit it when clicked. It inherits from L<IUP::GL::SubCanvas|IUP::GL::SubCanvas> and exists only inside an L<IUP::GL::CanvasBox|IUP::GL::CanvasBox>. Internally it uses an L<IUP::Text|IUP::Text> when the user clicks the control to allow editing of the text. Once the internal L<IUP::Text|IUP::Text> loses its focus the text is updated and the L<IUP::Text|IUP::Text> is hidden. The L<IUP::Text|IUP::Text> is an internal child of the element, and the application can use the L<IUP::GetChild|IUP::GetChild> function to access it. (since iup-3.19)

=head1 USAGE

=head2 CREATION - new() method

 my $txt = IUP::GL::Text->new();

B<Returns:> the identifier of the created element, or C<undef> if an error occurs.

=head2 ATTRIBUTES

For more info about concept of attributes (setting/getting values etc.)
see L<IUP::Manual::03_Attributes|IUP::Manual::03_Attributes>. Attributes specific to this element:

=over

=item B<ALIGNMENT>

I<(non inheritable)>

Horizontal and vertical alignment.
Possible values: "ALEFT", "ACENTER" and "ARIGHT", combined to "ATOP",
"ACENTER" and "ABOTTOM". Default: "ALEFT:ATOP". Partial values are also
accepted, like "ARIGHT" or ":ATOP", the other value will be obtained
from the default value. When editing only the horizontal alignment is used.

=item L<FGCOLOR|IUP::Manual::03_Attributes/FGCOLOR>

Text color. Can have an alpha component. Default: "0 0 0".

=item B<PADDING>

I<(non inheritable)>

Internal margin. Default value: "2x2".

=item B<CPADDING>

Same as PADDING but using the units of the B<SIZE> attribute. It will actually set the PADDING attribute. (since iup-3.29)

=item L<SIZE|IUP::Manual::03_Attributes/SIZE>

I<(non inheritable)>

Since the contents can be changed by the user, the B<Natural Size> is not affected by the text contents. Use VISIBLECOLUMNS and VISIBLELINES to control the B<Natural Size>.

=item B<TEXT>

I<(non inheritable)>

Returns the name of the internal L<IUP::Text|IUP::Text> used to edit the text when the user clicks the control. Another way to get access to the internal child L<IUP::Text|IUP::Text>.

=item B<TEXT_HANDLE>

I<(non inheritable)>

Returns the Ihandle of the internal L<IUP::Text|IUP::Text>.

=item B<VALUE>

I<(non inheritable)>

Text entered by the user.

=item B<VISIBLECOLUMNS>

Defines the number of visible columns for the B<Natural Size>, this means that will act also as minimum number of visible columns. It uses a wider character size than the one used for the SIZE attribute so strings will fit better without the need of extra columns. As for SIZE you can set to C<undef> after map to use it as an initial value. Default: 5.

=back

The following L<common attributes|IUP::Manual::03_Attributes/Common Attributes> are also accepted:

=over

=item * L<ACTIVE|IUP::Manual::03_Attributes/ACTIVE>,
L<FONT|IUP::Manual::03_Attributes/FONT>,
L<EXPAND|IUP::Manual::03_Attributes/EXPAND>,
L<SCREENPOSITION|IUP::Manual::03_Attributes/SCREENPOSITION>,
L<POSITION|IUP::Manual::03_Attributes/POSITION>,
L<MINSIZE|IUP::Manual::03_Attributes/MINSIZE>,
L<MAXSIZE|IUP::Manual::03_Attributes/MAXSIZE>,
L<WID|IUP::Manual::03_Attributes/WID>,
L<TIP|IUP::Manual::03_Attributes/TIP>,
L<SIZE|IUP::Manual::03_Attributes/SIZE>,
L<RASTERSIZE|IUP::Manual::03_Attributes/RASTERSIZE>,
L<ZORDER|IUP::Manual::03_Attributes/ZORDER>,
L<VISIBLE|IUP::Manual::03_Attributes/VISIBLE>

=back

=head2 CALLBACKS

For more info about concept of callbacks (setting callback handlers etc.)
see L<IUP::Manual::04_Callbacks|IUP::Manual::04_Callbacks>. Callbacks specific to this element:

=over

=item B<VALUECHANGED_CB>

Called after the value was interactively changed by the user.

B<Callback handler prototype:>

 sub valuechanged_cb_handler {
   my ($self) = @_;
   #...
 }

=over

B<$self:> reference to the element (IUP::GL::Text) that activated the event

=back

=back

The following L<common callbacks|IUP::Manual::04_Callbacks/Common Callbacks> are also accepted:

=over

=item * L<MAP_CB|IUP::Manual::04_Callbacks/MAP_CB>,
L<UNMAP_CB|IUP::Manual::04_Callbacks/UNMAP_CB>,
L<GETFOCUS_CB|IUP::Manual::04_Callbacks/GETFOCUS_CB>,
L<KILLFOCUS_CB|IUP::Manual::04_Callbacks/KILLFOCUS_CB>,
L<ENTERWINDOW_CB|IUP::Manual::04_Callbacks/ENTERWINDOW_CB>,
L<LEAVEWINDOW_CB|IUP::Manual::04_Callbacks/LEAVEWINDOW_CB>,
L<K_ANY|IUP::Manual::04_Callbacks/K_ANY>,
L<HELP_CB|IUP::Manual::04_Callbacks/HELP_CB>

=back

=head1 NOTES

Visually the difference between an B<IUP::GL::Text> and an L<IUP::GL::Button|IUP::GL::Button> is that by default the border is always visible in the B<IUP::GL::Text>.

=head1 EXAMPLES


Unfortunately there are no sample scripts using this element.



=head1 SEE ALSO

L<IUP::Text|IUP::Text>, L<IUP::GL::CanvasBox|IUP::GL::CanvasBox>

The original doc: L<iupgltext.html|http://www.tecgraf.puc-rio.br/iup/en/gl/iupgltext.html>


=cut
