=for comment based on iup-3.5-XXX-UNFINISHED

=head1 NAME

IUP::Sbox - [GUI element] container for expanding/contracting the child size in one direction

=head1 DESCRIPTION

Creates a void container that allows its child to be resized. Allows
expanding and contracting the child B<size> in one direction.

It does not have a native representation but it contains also a
L<IUP::Canvas|IUP::Canvas> to implement the bar handler.

=head1 USAGE

=head2 CREATION - new() method

 $sbox = IUP::Sbox->new(Ihandle* child);
 iup.sbox{child: ihandle} -> (elem: ihandle) [in Lua]
 sbox(child) [in LED]

B<child>: Identifier of an interface element which will receive the
box. It can be NULL.

NOTE: You can pass to C<new()> other C<ATTRIBUTE=E<gt>'value'> or C<CALLBACKNAME=E<gt>\&func> pairs relevant
to this element - see L<IUP::Manual::02_Elements|IUP::Manual::02_Elements>.

B<Returns:> the identifier of the created element, or C<undef> if an error occurs.

=head2 ATTRIBUTES

For more info about concept of attributes (setting/getting values etc.)
see L<IUP::Manual::03_Attributes|IUP::Manual::03_Attributes>. Attributes specific to this element:

=over

=item * B<COLOR>

Changes the color of the bar handler. The value should be
given in "R G B" color style. Default: "192 192 192".

=item * B<DIRECTION> (creation only)

Indicates the direction of the resize and
the position of the bar handler. Possible values are "NORTH", "SOUTH"
(vertical direction), "EAST" or "WEST" (horizontal direction). Default:
"EAST".

=item * L<EXPAND|IUP::Manual::03_Attributes/EXPAND> (non inheritable)

It will expand
automatically only in the direction opposite to the handler.

=item * B<WID> (read-only)

returns -1 if mapped.

=back

The following L<common attributes|IUP::Manual::03_Attributes/Common Attributes> are also accepted:

=over

=item * L<FONT|IUP::Manual::03_Attributes/FONT>, L<SIZE|IUP::Manual::03_Attributes/SIZE>,
L<RASTERSIZE|IUP::Manual::03_Attributes/RASTERSIZE>,
L<CLIENTSIZE|IUP::Manual::03_Attributes/CLIENTSIZE>,
L<CLIENTOFFSET|IUP::Manual::03_Attributes/CLIENTOFFSET>,
L<POSITION|IUP::Manual::03_Attributes/POSITION>,
L<MINSIZE|IUP::Manual::03_Attributes/MINSIZE>,
L<MAXSIZE|IUP::Manual::03_Attributes/MAXSIZE>

also accepted.

=back

=head1 NOTES

The controls that you want to be resized must have the EXPAND=YES
attribute set. The control inside the sbox will not be resized with a
size lesser than its B<Natural> size. See the L<Layout
Guide|../layout_guide.html> for mode details on sizes.

The L<IUP::Canvas|IUP::Canvas> bar handler is always the first child of the sbox. It
can be obtained using L<IUP::GetChild|IUP::GetChild> or B< IUP::GetNextChild>.

L<IUP::Sbox|IUP::Sbox> can be resized above the maximum size so some controls go to
outside the dialog area at right or bottom. In fact this is part of the
dynamic layout default reposition of controls inside the dialog. See
the L<IUP::Refresh|IUP::Refresh> function. The IUP layout does not have a maximum
limit only a minimum, except if you use the MAXSIZE common attribute.

The box can be created with no elements and be dynamic filled using
L<IUP::Append|IUP::Append> or
L<IUP::Insert|IUP::Insert>.

=head1 EXAMPLES

L<Browse for Example Files|../../examples/>

[IMAGE]

Natural Size

[IMAGE]

After Expanding the Sbox

[IMAGE]

Expanding the Dialog

[IMAGE]

After Expanding the Sbox

=cut