=for comment based on iup-3.9 (attributes refreshed to iup-3.32) - http://www.tecgraf.puc-rio.br/iup/en/elem/iupscrollbox.html

=head1 NAME

IUP::ScrollBox - [GUI element] container that allows its child to be scrolled

=head1 DESCRIPTION

Creates a native container that allows its child to be scrolled. It
inherits from L<IUP::Canvas|IUP::Canvas>.

=begin HTML

<p>
<img src="http://kmx.github.io/perl-iup/img-3.9/elem/iupscrollbox.png ">
</p>

=end HTML

=head1 USAGE

=head2 CREATION - new() method

 #standard way
 $mlist = IUP::ScrollBox->new( child=>$child, ANYATTRIBUTE=>'any value' );
 #or with just 1 parameter
 $mlist = IUP::ScrollBox->new($child);

B<child:> (named parameter) reference to an interface element.

B<Returns:> the identifier of the created element, or C<undef> if an error occurs.

NOTE: You can pass to C<new()> other C<ATTRIBUTE=E<gt>'value'> or C<CALLBACKNAME=E<gt>\&func> pairs relevant
to this element - see L<IUP::Manual::02_Elements|IUP::Manual::02_Elements/"new()">.

=head2 ATTRIBUTES

For more info about concept of attributes (setting/getting values etc.)
see L<IUP::Manual::03_Attributes|IUP::Manual::03_Attributes>. Attributes specific to this element:

Inherits all attributes and callbacks of the L<IUP::Canvas|IUP::Canvas>, but redefines a few attributes.

=over

=item L<BGCOLOR|IUP::Manual::03_Attributes/BGCOLOR>

will use the background color of the native parent by default.

=item B<BORDER>

I<(creation only)> the default value is "NO".

=item B<CANFOCUS>

Is set to NO.

=item B<CANVASBOX>

I<(non inheritable)>

Enable the behavior of a canvas box instead of a regular container. This will
affect the EXPAND attribute, the natural size computation, and child layout
distribution. Can be Yes or No. Default: No. (since iup-3.20)

=item B<CHILDOFFSET>

Allow to specify a position offset for the child. Available for native
containers only. It will not affect the natural size, and allows to position
controls outside the client area. Format "I<dx>xI<dy>", where I<dx> and I<dy>
are integer values corresponding to the horizontal and vertical offsets,
respectively, in pixels. Default: 0x0. (since iup-3.14)

=item L<EXPAND|IUP::Manual::03_Attributes/EXPAND>

I<(non inheritable)> the default value is "YES".

=item B<LAYOUTDRAG>

I<(non inheritable) [Windows Only]>

When the scrollbar is moved automatically update the children layout. Default:
YES. If set to NO then the layout will be updated only when the mouse drag is
released. (since iup-3.19)

=item L<SCROLLBAR|IUP::Manual::03_Attributes/SCROLLBAR>

I<(creation only)> the default value is "YES".

=item B<SCROLLTO>

I<(write-only)>

Position the scroll at the given x,y coordinates relative to the box top-left
corner. Format "I<x,y>". Value can also be TOP or BOTTOM for a vertical scroll
to the top or to the bottom of the scroll range. (since iup-3.17)

=item B<SCROLLTOCHILD>

I<(write-only)>

Position the scroll at the top-left corner of the given child located by its
name. Use L<IUP::SetHandle|IUP::SetHandle> or L<IUP::SetAttributeHandle|IUP::SetAttributeHandle>
to associate an element to a name. The child must be contained in the ScrollBox
hierarchy. (since iup-3.17)

=item B<WHEELDROPFOCUS>

Set to Yes. (since iup-3.28)

=item L<CLIENTSIZE|IUP::Manual::03_Attributes/CLIENTSIZE>, L<CLIENTOFFSET|IUP::Manual::03_Attributes/CLIENTOFFSET> also accepted.

=back

=head2 CALLBACKS

For more info about concept of callbacks (setting callback handlers etc.)
see L<IUP::Manual::04_Callbacks|IUP::Manual::04_Callbacks>. Callbacks specific to this element:

=over

=item B<LAYOUTUPDATE_CB>

Action generated when the layout is updated (after scrolling or
resizing), so the application can reposition its own children.

B<Callback handler prototype:>

 sub layoutupdate_cb_handler {
   my ($self) = @_;
   #...
 }

B<$self:> reference to the element (L<IUP::ScrollBox|IUP::ScrollBox>) that activated the event.

=back

The following L<common callbacks|IUP::Manual::04_Callbacks/Common Callbacks> are also accepted:

=over

=item * L<MAP_CB|IUP::Manual::04_Callbacks/MAP_CB>,
L<UNMAP_CB|IUP::Manual::04_Callbacks/UNMAP_CB>,
L<GETFOCUS_CB|IUP::Manual::04_Callbacks/GETFOCUS_CB>,
L<KILLFOCUS_CB|IUP::Manual::04_Callbacks/KILLFOCUS_CB>,
L<ENTERWINDOW_CB|IUP::Manual::04_Callbacks/ENTERWINDOW_CB>,
L<LEAVEWINDOW_CB|IUP::Manual::04_Callbacks/LEAVEWINDOW_CB>,
L<K_ANY|IUP::Manual::04_Callbacks/K_ANY>,
L<HELP_CB|IUP::Manual::04_Callbacks/HELP_CB>

=back

=head1 NOTES

The box allows the application to create a virtual space for the dialog
that is actually larger than the visible area. The current size of the
box defines the visible area. The natural size of the child (and its
children) defines the virtual space size. So the L<IUP::ScrollBox|IUP::ScrollBox> does
not depend on its child size or expansion, and its natural size is
always "0x0".

The user can move the box contents by dragging the background. Also the
mouse wheel scrolls the contents vertically.

The box can be created with no elements and be dynamic filled
using L<Append|IUP::Manual::02_Elements/"Append()"> or L<Insert|IUP::Manual::02_Elements/"Insert()">.

=head1 EXAMPLES


Unfortunately there are no sample scripts using this element.



=head1 SEE ALSO

The original doc: L<iupscrollbox.html|http://www.tecgraf.puc-rio.br/iup/en/elem/iupscrollbox.html>


=cut