=head1 NAME

IUP::Separator - [GUI element] shows a line between two menu items

=head1 DESCRIPTION

Creates the separator interface element. It shows a line between two
menu items.

=head1 USAGE

=head2 CREATION - new() method

 $separator = IUP::Separator->new(void);
 iup.separator{} -> (elem: ihandle) [in Lua]
 separator() [in LED]

NOTE: You can pass to C<new()> other C<ATTRIBUTE=E<gt>'value'> or C<CALLBACKNAME=E<gt>\&func> pairs relevant
to this element - see L<IUP::Manual::02_Elements|IUP::Manual::02_Elements>.

B<Returns:> the identifier of the created element, or C<undef> if an error occurs.

=head1 NOTES

The separator is ignored when it is part of the definition of the items
in a bar menu.

=head1 EXAMPLES

L<Browse for Example Files|../../examples/>

=head1 SEE ALSO

L<IUP::Item|IUP::Item>, L<IUP::SubMenu|IUP::SubMenu>,
L<IUP::Menu|IUP::Menu>.

=cut