=head1 NAME

IUP::User - [special] user element which is not associated to any interface element

=head1 DESCRIPTION

Creates a user element in IUP, which is not associated to any interface
element. It is used to map an external element to a IUP element. Its
use is usually done by CPI elements, but you can use it to create an
Ihandle* to store private attributes.

=head1 USAGE

=head2 CREATION - new() method

 $user = IUP::User->new(void);
 iup.user{} -> (elem: ihandle) [in Lua]
 user() [in LED]

NOTE: You can pass to C<new()> other C<ATTRIBUTE=E<gt>'value'> or C<CALLBACKNAME=E<gt>\&func> pairs relevant
to this element - see L<IUP::Manual::02_Elements|IUP::Manual::02_Elements>.

B<Returns:> the identifier of the created element, or C<undef> if an error occurs.

=head2 ATTRIBUTES

B<CLEARATTRIBUTES> (write-only, non inheritable): it will clear all
attributes stored internally and remove all references. 

=cut