=head1 CD_SVG - Scalable Vector Graphics Driver (cdsvg.h)

This driver allows the generation of a SVG file, a modularized language
for describing two-dimensional vector and mixed vector/raster graphics
in XML. The L<SVG specification|http://www.w3.org/TR/SVG/> is an open
standard that has been under development by the L<World Wide Web
Consortium|http://www.w3.org/> (W3C) since 1999.

=head2 Use

The file is created by calling function
L<B<cdCreateCanvas>|../func/init.html#cdCreateCanvas>(CD_SVG, Data).
The Data parameter is a string that must contain the filename and the
canvas dimensions, in the following format:

 "filename [widthxheight] [resolution]" or in C "%s %gx%g %g"

Only the parameter filename is required. The filename must be inside
double quotes (") if it has spaces. Width and height are provided in
millimeters (note the lowercase "x" between them), and their default
value in pixels is INT_MAX for both dimensions. Resolution is the
number of pixels per millimeter; its default value is "3.78 pixels/mm"
(96 DPI). Width, height and resolution are real values.

Any amount of such canvases may exist simultaneously. It is important
to note that a call to function L<B<
cdKillCanvas>|../func/init.html#cdKillCanvas> is required to B<close>
the file properly.

B<IMPORTANT:> because the SVG specification states that floating point
number must use dots "." for floating point separators, we set the
numeric locale to "C" when the canvas is created, and restore it when
it is destroyed. But since it uses the global C function B<setlocale>
if you use other C functions that are locale dependent while the SVG
canvas is being used then be aware that they will be affected.

=head2 Behavior of Functions

=head2 Control

L<B<Play>|http://www.tecgraf.puc-rio.br/cd/en/func/other.html#cdPlay>:
does nothing, returns CD_ERROR.

L<B<Clear>|http://www.tecgraf.puc-rio.br/cd/en/func/control.html#cdClear>:
does nothing.

=head2 Coordinate System and Clipping

L<B<UpdateYAxis>|../func/coordinates.html#cdUpdateYAxis>: does nothing.

B<Complex Regions>: not supported.

=head2 Attributes

L<B<FontDim>|http://www.tecgraf.puc-rio.br/cd/en/func/text.html#cdFontDim>:
is simulated.

L<B<TextSize>|http://www.tecgraf.puc-rio.br/cd/en/func/text.html#cdTextSize>:
is simulated.

L<B<WriteMode>|http://www.tecgraf.puc-rio.br/cd/en/func/attributes.html#cdWriteMode>:
does nothing, returns CD_REPLACE.

=head2 Colors

L<B< GetColorPlanes>|../func/color.html#cdGetColorPlanes>: always
returns 24.

L<B<Palette>|http://www.tecgraf.puc-rio.br/cd/en/func/color.html#cdPalette>:
does nothing.

=head2 Primitives

B<L<Pixel|http://www.tecgraf.puc-rio.br/cd/en/func/marks.html#cdPixel>>:
does not exist in SVG, is simulated using a circle with radius=0.1.

Floating point primitives are supported.

=head2 Client Images

L<B<GetImageRGB>|../func/client.html#cdGetImageRGB>: does nothing.

=head2 Server Images

All functions do nothing.

=head2 Exclusive Attributes

=over

=item * "B<CMD>": saves a string directly to the file. Allows adding
SVG commands to the file generated by the CD library. (set only)

=back

=over

=item * "B<OPACITY>": allows the usage of a global opacity value. The
value passed must be a string containing an integer ("%d") [0=full
transparent, 255=full opaque]. Use NULL to reset to the default.
Default: 255.

=back

=over

=item * B<"HATCHBOXSIZE">: defines the size of smallest hatch box
pattern. This affects the spacing between the hatch lines. The value
passed must be a string containing an integer ("%d"). If the value of
the attribute passed is NULL, the value is rest to the default. When
consulted returns the current value ("%d"). Default: "8".

=back

=cut