=head1 SHOW_CB

Called right after the dialog is showed, hidden, maximized, minimized
or restored from minimized/maximized. This callback is called when
those actions were performed by the user or programmatically by the
application.

=head2 Callback

 int function(Ihandle *ih, int state); [in C]
 elem:show_cb(state: number) -> (ret: number) [in Lua]

B<ih>: identifier of the element that activated the event.

B<state:> indicates which of the following situations generated the
event:

=over

IUP_HIDE (since 3.0)

IUP_SHOW

IUP_RESTORE (was minimized or maximized)

IUP_MINIMIZE

IUP_MAXIMIZE (since 3.0) (not received in Motif when activated from the
maximize button)

=back

Returns: IUP_CLOSE will be processed.

=head2 Affects

L<IupDialog|../dlg/iupdialog.html>

=cut