=head1 DESTROY_CB

Called right before an element is destroyed.

=head2 Callback

 int function(Ihandle *ih); [in C]
 elem:destroy_cb() -> (ret: number) [in Lua]

B<ih>: identifier of the element that activated the event.

=head2 Notes

For language binding implementations use the callback name
"LDESTROY_CB" to release memory allocated by the binding for the
element. This callback will be called before "DESTROY_CB".

=head2 Affects

All.

=cut