=head1 DROPFILES_CB

Action called when a file is "dropped" into the control. When several
files are dropped at once, the callback is called several times, once
for each file.

If defined after the element is mapped then the attribute
DROPFILESTARGET must be set to YES.

[Windows and GTK Only] (GTK 2.6)

=head2 Callback

 int function(Ihandle *ih, const char* filename, int num, int x, int y); [in C]
 elem:dropfiles_cb(filename: string; num, x, y: number) -> (ret: number) [in Lua]

B<ih>: identifier of the element that activated the event.

B<filename>: Name of the dropped file.

B<num>: Number index of the dropped file. If several files are dropped,
B<num> is the index of the dropped file starting from "total-1" to "0".

B<x>: X coordinate of the point where the user released the mouse
button.

B<y>: Y coordinate of the point where the user released the mouse
button.

Returns: If IUP_IGNORE is returned the callback will NOT be called for
the next dropped files, and the processing of dropped files will be
interrupted.

=head2 Affects

L<IupDialog|../dlg/iupdialog.html>,
L<IupCanvas|../elem/iupcanvas.html>,
L<IupGLCanvas|../ctrl/iupglcanvas.html>,
L<IupText|../elem/iuptext.html>, L< IupList|../elem/iuplist.html>

=cut