=head1 LED

LED is a dialog-specification language whose purpose is not to be a
complete programming language, but rather to make dialog specification
simpler than in C.

In LED, attributes and expressions follow this form:

elem =
element[B<attribute1=value1,attribute2=value2,>...](...expression...)

The names of the elements must not contain the iup prefix. Attribute
values are always interpreted as strings, but they need to be in quotes
() only when they include spaces. The IUP_ prefix must not be added to
the names of the attributes and predefined values. Expressions contain
parameters for creating the element.

In LED there is no distinction between upper and lower case, except for
attribute names.

The L<IupLoad|func/iupload.html> function can parse a text file and
create the IUP elements defined in it. Naturally, the same file cannot
be loaded more than once, because the elements would be created again.
The file parse does not map the elements to the native system.

The LED files are dynamically loaded and must be packaged together with
the applications executable. However, this often becomes an
inconvenience. To deal with it, there is the L<LEDC|ledc.html> compiler
that creates a C module from the LED contents.

To simply view a LED file objects use the LED Viewer application called
L<IupView|executables.html>, in the applications included in the
distribution. Pre-compiled binaries are available at the
L<Download|download.html>.

=cut