=head1 To Do

=head2 Roadmap for the Next Versions

B<Working now> on IupPPlot, studding possible use of
L<PLplot|http://plplot.sourceforge.net/> as a replacement.

=over

=item * IupTree, IupList and IupMatrix improvements

=item * New controls: ScrollBox, GridBox

=item * UTF-8 in all drivers and in text callbacks

=item * New dialogs: Scripter

=item * RPM, Debian and LuaRocks packages

=back

[Suggestions?]

=head2 General

=over

=item * B<Priority:> Images in B< IupList>.

=item * B<Priority:> RPM, Debian and LuaRocks distribution packages.

=item * B<Priority:> Unicode Support (UTF-8) in Windows and Motif.

=item * B<Priority:> Drag&Drop between controls.

=item * B<Priority:> A tutorial section in the documentation. One big
Controls Demo just like GTK, wxWidgets and Qt have.

=item * B<Priority:> Customization of B<IupGetParam> to add other
applications controled elements.

=item * B<Priority:> detection of the minimum size of a child inside
B<IupSplit>.

=item * A MacOS X native driver using Carbon or Cocoa.

=item * B<IupGLCanvas> for MacOSX.

=item * The actual model for control data structure in the internal SDK
is restricted for derived classes.

=item * Loading and saving RTF files in B<IupText>. Add support for
images inside the text.

=item * Possibility to change the system menu in Windows. Support for
cascading B< IupPopup> for menus.

=item * Support for Portuguese in the B<IupView> application.

=item * Vertical text in labels and buttons.

=back

=head2 Windows

=over

=item * Known Issue: when an B<IupVal> is inside an B<IupTabs>, the
tabs disappear when the mouse moves over it after being used in the
valuator. A workaround is to put the valuator inside an B<IupFrame> and
then inside the B< IupTabs>, so the problem does not occur.

=item * Known Issue: when the dialog background is dynamically changed
the B<IupVal> background is only updated after the user click on the
control or when the control is redisplayed.

=item * Known Issue: in Windows Vista the COMPOSITE=YES attribute of
the B<IupDialog> is not working as expected. There is still flicker
when the dialog is resized. B<IupTabs> in Windows Vista when
COMPOSITE=YES works only if MULTILINE=YES. (since 3.0)

=item * Known Issue: the MDI Window menu is not properly updated when
the child mdi is closed. (since 3.0)

=item * Known Issue: in Windows when CANFOCUS=NO only the Tab key
navigation is not done, when clicked the control will still get the
focus. The only exceptions are button and canvas.

=item * Known Issue (Compiler): the B<IupImgLib> takes an very long
time to compile under Visual C++. (since 3.0)

=item * Known Issue (Compiler): when building with Open Watcom the
additional controls crash. When you add debug information to the main
IUP library the problem solves. We tried to track down this error but
it does not occurs with debug information and our attempts without
debug does not gives any results. So the IUP main library for Watcom is
now distributed with debug information. (since 3.0)

=back

=head2 Motif

=over

=item * Known Issue: when the B<IupList> has DROPDOWN=Yes in Motif, and
the list has items with the same string, the ACTION callback will
return the index of the item with the first instance of the string
only. This seems to be a bug or limitation in Motif.

=back

=head2 IupMatrix

=over

=item * B<Priority:> Other columns/lines fixed at start like column 0
and line 0.

=item * B<Priority: >image, check mark and gauge for cells.

=item * Mark using the keyboard.

=item * Drag&drop of columns position.

=back

=head2 IupTree

=over

=item * B<Priority:> check mark for nodes.

=item * Known Issue: the rubber band gets lost depending on what you do
inside the SELECTION_CB callback in GTK. To avoid that set
RUBBERBAND=NO.

=item * Known Issue: the SELECTION_CB callback may be called more than
once for the same node with the same status.

=item * Known Issue: in Windows XP, when using a font for an node with
TITLEFONTid in B<IupTree> that is larger than the element FONT the item
text will be cropped at right and bottom because the system uses the
element font to calculate the item size. The only exception is when you
just change the font to add a Bold style.

=item * Important: old NAMEid attribute conflicts with the common
attribute NAME. Should be replaced by the new TITLEid. NAMEid will be
removed in future versions. (since 3.0)

=item * RENAMEEDIT_CB callback and RENAMEMASKid attribute.

=item * Add new nomenclature option for id, for example ":2:1:4"

=item * Define minimum size based on tree nodes.

=item * drag&drop of multiple selected nodes.

=back

=head2 IupPPlot

=over

=item * Allow to select multiple nodes at once dragging the mouse
within a region.

=item * Add support of legend text near each dataset plot.

=item * Adjust AutoScale to start and end at major axis ticks.

=item * Improve the display of values near each sample.

=item * Custom legend position.

=item * PPlot force the definitions of the margins. It should have a
way to automatic calculate the margins when doing automatic scaling.

=item * PPlot force the Grid to be automatically spaced following the
major ticks.

=item * PPlot generates lots of warnings on all compilers.

=back

=head2 New Controls

=over

=item * B<Priority: Scripter - >Project Manager/Dialog
Editor/Integrated Debugger for IupLua

=item * B<Priority: ScrollBox> - a box that can scroll the elements
inside

=item * B<Priority: GridBox >- container to distribute elements in a
grid.

=item * -----------------------------

=item * B<DropDownButton> - Mix between a drop down list and a button

=item * B<CanvasCD> - an IupCanvas with a CD canvas associated.

=item * B<Scrollbar> - just the scrollbar as a control.

=item * B<Toobar -> button/toggle/list, detachable

=item * B<Table> - similar to IupMatrix but using native controls

=item * B<UrlButton> - Button that activates a URL (looks like a flat
label, but gives visual feedback when mouse is hover)

=item * B<FrameEx> - Expandable/Closeable Frames

=item * B<PropertyGrid> - a 2 column matrix with expandable/closeable
items

=item * -----------------------------

=item * Lookup Table, maps a set of values in another set using a
curve.

=item * Statusbar

=item * Calendar

=back

=cut