=head1 To Do

=head2 Roadmap for the Next Versions

=head2 For Next Version (3.10 - January 2014)

=over

=item * Processing feedback in the taskbar on Window 7

=item * DND simple support for B<IupList> and B<IupTree> to allow DND
from list to list, and tree to tree.

=item * Improvements in B<IupWebBrowser>

=item * Close button for a tab in B<IupTabs>

=item * A detachable box

=item * Support for image and text simultaneously on B<IupLabel>

=back

=head2 Other Priorities

=over

=item * OpenGL sub-canvas controls

=item * Consolidate a plot control

=item * Interactive Dialog Editor / Tools to improve productivity

=item * Tutorial section and code snippets collection

=back

=head2 General

=over

=item * B<Priority:> remove DEPRECATED functions and headers in IUP 4.0

=item * B<Priority:> Interactive Dialog Editor

=item * B<Priority:> A tutorial section in the documentation. One big
Controls Demo just like GTK, wxWidgets and Qt have. Code snippets
collection.

=item * B<Priority:> support for image and text at the same time in
B<IupLabel>.

=item * B<Important:> RPM, Debian and LuaRocks distribution packages.

=item * B<Important: IupGLCanvas> in MACOS X using native OpenGL
support.

=item * B<Important: > A MacOS X native driver using Carbon or Cocoa.

=item * The actual model for control data structure in the internal SDK
is restricted for derived classes.

=item * Loading and saving RTF files in B<IupText>. Add support for
images inside the text.

=item * Possibility to change the system menu in Windows. Support for
cascading B< IupPopup> for menus.

=item * Support for Portuguese in the B<IupView> application.

=item * Vertical text in labels and buttons.

=back

=head2 Windows

=over

=item * Known Issue: when in Windows 8 the B< IupFontDlg> dialog does
not supports the TITLE attribute nor can be positioned.

=item * Known Issue: when an B<IupVal> is inside an B<IupTabs>, the
tabs disappear when the mouse moves over it after being used in the
valuator. A workaround is to put the valuator inside an B<IupFrame> and
then inside the B< IupTabs>, so the problem does not occur.

=item * Known Issue: when the dialog background is dynamically changed
the B<IupVal> background is only updated after the user click on the
control or when the control is redisplayed.

=item * Known Issue: in Windows Vista the COMPOSITE=YES attribute of
the B<IupDialog> is not working as expected. There is still flicker
when the dialog is resized. B<IupTabs> in Windows Vista when
COMPOSITE=YES works only if MULTILINE=YES. (since 3.0)

=item * Known Issue: in Windows when CANFOCUS=NO only the Tab key
navigation is not done, when clicked the control will still get the
focus. The only exceptions are button and canvas.

=item * Known Issue (Compiler): the B<IupImgLib> takes an very long
time to compile under Visual C++. (since 3.0)

=item * Known Issue (Compiler): when building with Open Watcom the
additional controls crash. When you add debug information to the main
IUP library the problem solves. We tried to track down this error but
it does not occurs with debug information and our attempts without
debug does not gives any results. So the IUP main library for Watcom is
now distributed with debug information. (since 3.0)

=back

=head2 GTK

=over

=item * Known Issue: can not set focus to a child inside TABCHANGE_CB
or TABCHANGEPOS_CB in B<IupTabs>, because internally GTK will always
set the focus to the first child.

=item * Known Issue: in Ubuntu 11.10 the canvas scrollbar is not
notifying IUP that the user dragged the control. To solve the problem
remove the overlay-scrollbar, this is the package that makes the
scrollbar invisible until the mouse is near it.

=back

=head2 Motif

=over

=item * Known Issue: when the B<IupList> has DROPDOWN=Yes in Motif, and
the list has items with the same string, the ACTION callback will
return the index of the item with the first instance of the string
only. This seems to be a bug or limitation in Motif.

=item * Known Issue: an element when inside an B<IupScrollBox> is not
being displayed until the box is scrolled if its size alone is greater
than the scrollbox visible size.

=item * Known Issue: B<IupMatrix> crash the application during its
creation on OpenMotif 2.3.3. inside the creation of the internal
B<IupList>.

=back

=head2 IupMatrix

=over

=item * Drag&drop of columns, i.e. interactive change of column
position.

=back

=head2 IupTree

=over

=item * Known Issue: the rubber band gets lost depending on what you do
inside the SELECTION_CB callback in GTK. To avoid that set
RUBBERBAND=NO.

=item * Known Issue: the SELECTION_CB callback may be called more than
once for the same node with the same status.

=item * Known Issue: in Windows XP, when using a font for an node with
TITLEFONTid in B<IupTree> that is larger than the element FONT the item
text will be cropped at right and bottom because the system uses the
element font to calculate the item size. The only exception is when you
just change the font to add a Bold style.

=item * Important: old NAMEid attribute conflicts with the common
attribute NAME. Should be replaced by the new TITLEid. NAMEid will be
removed in future versions. (since 3.0)

=item * RENAMEEDIT_CB callback and RENAMEMASKid attribute.

=item * Add new nomenclature option for id, for example ":2:1:4"

=item * Define minimum size based on tree nodes.

=item * drag&drop of multiple selected nodes.

=back

=head2 IupPPlot

=over

=item * Allow to select multiple nodes at once dragging the mouse
within a region.

=item * Add support of legend text near each dataset plot.

=item * Adjust AutoScale to start and end at major axis ticks.

=item * Improve the display of values near each sample.

=item * Custom legend position.

=item * PPlot force the definitions of the margins. It should have a
way to automatic calculate the margins when doing automatic scaling.

=item * PPlot force the Grid to be automatically spaced following the
major ticks.

=item * PPlot generates lots of warnings on all compilers.

=back

=head2 IupMglPlot

=over

=item * Upgrade to the MathGL version 2.

=back

=head2 Possible New Controls

=over

=item * B<DropDownButton> - Mix between a drop down list and a button

=item * B<Table> - similar to IupMatrix but using native controls
(Windows,GTK,Motif)

=item * B<Scripter - >Project Manager/Dialog Editor/Integrated Debugger
for IupLua

=item * B<CanvasCD> - an IupCanvas with a CD canvas associated.

=item * B<Scrollbar> - just the scrollbar as a control.
(Windows,GTK,Motif)

=item * -----------------------------

=item * Toobar - button/toggle/list, detachable

=item * PropertyGrid - a 2 column matrix with expandable/closeable
items

=item * Lookup Table, maps a set of values in another set using a
curve.

=item * Progress Indicator - a simpler version of the IupProgressBar

=item * Horizontal List

=item * Statusbar (Windows,GTK)

=item * Spinner (GTK)

=item * Calendar (Windows)

=item * IP Address (Windows)

=back

=cut